### ISSUE TITLE
Member Roles

### ISSUE THREAD

**Issue by Marc3llo** [download-monitor/download-monitor#194]
Hello, very nice plugin, however, does it not support to be accessible for _editors_ for example?
Did I miss out on something?

**Comment by barrykooij** [comment]
The downloads post type and it's overview and edit screens have their own capability: manage_downloads. On plugin installation only the admin role is given this capability. You can definitely add this capability to other roles as well, but this would be something you have to code yourself. More information on the subject: http://codex.wordpress.org/Roles_and_Capabilities
