### ISSUE TITLE
Browse folder

### ISSUE THREAD

**Issue by ikaroweb** [download-monitor/download-monitor#195]
Why i can't browse folder e subfolder ?
And how can i come back to main folder ?

**Comment by barrykooij** [comment]
We're talking about the "Browse for file" button when adding new files to downloads right? Because this button is working fine for me.

![image](https://cloud.githubusercontent.com/assets/2846594/5606105/291f8256-941e-11e4-998b-5089d6fc26b4.png)

What version of the plugin and WordPress are you on?

**Comment by hacknug** [comment]
Yes! It triggers the modal but I can't get inside any of the folders it shows.

**Comment by barrykooij** [comment]
@hacknug @ikaroweb Is still still relevant in the latest version?
