### ISSUE TITLE
Conflict with Custom Meta Boxes

### ISSUE THREAD

**Issue by cehwitham** [download-monitor/download-monitor#196]
I've just posted an issue on the Human Made repo.

https://github.com/humanmade/Custom-Meta-Boxes/issues/271

There seems to be a script conflict that is causing the thickbox title to output multiple times when the CMB library is included as a MU plugin.

![screen shot 2014-10-28 at 09 42 33](https://cloud.githubusercontent.com/assets/2518941/4806688/e82e86ce-5e8b-11e4-8f08-7c5c7bced720.png)

This forces down the content of the thickbox and pushes the Insert Download out of view so you can't click on it.

**Comment by barrykooij** [comment]
Currently working on 1.6.0, please bear with me here :)

**Comment by filipvanreeth** [comment]
Thanks. 
Bedankt. 

Met vriendelijke groet, 
Filip

Verstuurd vanaf mijn iPhone

**Comment by barrykooij** [comment]
I've appear to have fixed this issue by moving all JS to separate files. You can test this by trying the enhancement/next-release branch. Please note this is a branch I develop in, don't try this on live websites. Branch: https://github.com/download-monitor/download-monitor/tree/enhancement/next-release

This fix will be included in 1.6.0

**Comment by filipvanreeth** [comment]
Thanks Bart.

Will look into it at soon as possible.

Regards,
Filip
