### ISSUE TITLE
endpoint doesn't work

### ISSUE THREAD

**Issue by OsoBear** [download-monitor/download-monitor#197]
If I set the endpoint to anything other than download, the add-on page stops working. Also links stop working. i.e. http://domain.com/library/download-category/the-category. This now returns Download does not exist. Go to homepage →

**Comment by codente** [comment]
I'm not able to reproduce this using the latest version.

**Comment by barrykooij** [comment]
Not able to reproduce it either.

@OsoBear I suspect that there is a plugin or theme conflict on your website. Could you please try if the error still occurs with only this plugin activated with a default WordPress theme (e.g. twentyfifteen). I understand this can be a bit of a hassle but it's the only way we can be sure it's a bug in this plugin.

**Comment by barrykooij** [comment]
Closing this due inactivity. Feel free to reopen this issue if you've tried above things and the problem still persists.
