### ISSUE TITLE
{content} not working internally

### ISSUE THREAD

**Issue by Horlix** [download-monitor/download-monitor#198]
Would there be a reason why the {content} tag is avalaiable and working on one site and not the other. We are using the same version of the plugin (3.3.5.9) and being used in the same way. One site is an intranet the other is external.

If you could point me in the right direction that would be fantastic.

Cheers
s

**Comment by barrykooij** [comment]
Looking at your version number it looks like you're using the legacy version of Download Monitor which isn't supported anymore. I suggest you upgrade to the latest version using this plugin and following it's instructions: https://wordpress.org/plugins/download-monitor-legacy-importer/
