### ISSUE TITLE
Download Options Seem to Be Broken

### ISSUE THREAD

**Issue by dRwH0** [download-monitor/download-monitor#199]
Hello and thanks for a great plugin.

I don't have an issue using it. Even if the files are hosted locally on my web-server, or remotely (via direct linking). What doesn't seem to work, and bothers me a lot, is the fact that I can't seem to select the Download Options --> Members Only (Or even Featured download / Redirect To File)

I select it, press update and then it seems to reset. Nothing remains ticked.

It really troubles me, because I want my users to log-in first, before downloading anything. 

I'm using WP 4.0.1 with Download Monitor 1.5.1.

Also on my site I use the following plugins and nothing more :

1. Akismet
2. All in One SEO Pack
3. Google Analytics
4. Sidebar Login
4. WP Post Views
5. WP Smush It
6. WP phpBB Bridge

**Comment by dRwH0** [comment]
Has this been addressed with the latest builds ?

**Comment by codente** [comment]
It works perfectly for me but always has.  Have you tried with all other plugins deactivated?

**Comment by barrykooij** [comment]
@dRwH0 Could you please like  @codente suggested testing this without other plugins activated. This functionality is working for me and I haven't got any other reports about this one.

**Comment by dRwH0** [comment]
Sorry to take this long to respond. I will try it out, with no plugins activated and get back to you.

Cheers,

**Comment by dRwH0** [comment]
Disabled all plugins - even phpBB Bridge. Still nothing. Even tried reverting to a basic theme, with still no plugins activated. Same result. Maybe because I used to have other download utils, my database might be messed up ?

Currently running WordPress 4.0.1 with Gameleon theme.

Tbh, if I'm the only one having this issue, then it's 99.99% sth is wrong in my setup - so no need to worry. For now, I'm using another plugin to lock the download pages I have created, instead of locking each file separately.  So, als good :)

**Comment by barrykooij** [comment]
I suspect something is wrong in your setup but it's hard to debug. You could always try if it works for you on a clean WP install. I understand that's quite a job to test it so I totally understand if that's too much work for you.

Feel free to reopen the issue if the problem still exists on a clean WP install. If it does, it might be a server related issue.
