### ISSUE TITLE
Scott was here.

### ISSUE THREAD

**Issue by scottbasgaard** [download-monitor/download-monitor#212]
@barrykooij https://www.youtube.com/watch?v=v1PBptSDIh8

**Comment by barrykooij** [comment]
![selfie-0](http://i.imgur.com/3sumHAt.gif)

**Comment by scottbasgaard** [comment]
@bryceadams

**Comment by bryceadams** [comment]
:japanese_ogre: :family: :ghost: :japanese_ogre: :family: :ghost: :japanese_ogre: :family: :ghost: :japanese_ogre: :family: :ghost: :japanese_ogre: :family: :ghost: :japanese_ogre: :family: :ghost: :japanese_ogre: :family: :ghost: :japanese_ogre: :family: :ghost: :japanese_ogre: :family: :ghost: :japanese_ogre: :family: :ghost: :japanese_ogre: :family: :ghost: :japanese_ogre: :family: :ghost: :japanese_ogre: :family: :ghost: :japanese_ogre: :family: :ghost: :japanese_ogre: :family: :ghost: :japanese_ogre: :family: :ghost: :japanese_ogre: :family: :ghost: :japanese_ogre: :family: :ghost:

**Comment by bryceadams** [comment]
@scottbasgaard
