### ISSUE TITLE
Page addon can't be activated

### ISSUE THREAD

**Issue by justinkruit** [download-monitor/download-monitor#215]
When you try to activate the Page Addon, it gives some error with javascript. 
With this reason, I can't activate the Page Addon. 

Can this be fixed? 

This happens with 1.6.0, and the updated Addon.

**Comment by barrykooij** [comment]
What JavaScript error do you get?

**Comment by barrykooij** [comment]
I've found the problem and fixed it. This will be release in the next version, most likely today. Sorry for the inconvenience.
