### ISSUE TITLE
Conflicts with Avada theme

### ISSUE THREAD

**Issue by barrykooij** [download-monitor/download-monitor#217]
I upgraded today with latest release and unfortunately it caused issues with Avada theme.

I was no longer able to set the featured image in post and pages.

I reverted back to last release and problem is fixed.

Just thought you might like to know as im sure many people use both DM and Avada together.

**Comment by GrantAustin** [comment]
I want to add that this isn't just with Avada theme. I found that this is happening on all themes.

**Comment by barrykooij** [comment]
Thanks for the info! :)

**Comment by brettmhoffman** [comment]
Same issue for me.

**Comment by barrykooij** [comment]
@GrantAustin and @brettmhoffman What themes do you have activated and what WP version are you on? I've tested with all default WP themes and it's working for me.

**Comment by GrantAustin** [comment]
@barrykooij I am running Wordpress 4.1. I am using a child theme of Studiopress.

**Comment by brettmhoffman** [comment]
Currently experiencing the issue on WP 4.1 using the Charity theme (http://themeforest.net/item/charity-foundationfundraising-wordpress-theme/6864259)

**Comment by barrykooij** [comment]
Could any of you please send a copy of the theme to git@barrykooij.nl 
I obviously would only use it for testing. Thanks in advance.

**Comment by GrantAustin** [comment]
@barrykooij Sent.

**Comment by barrykooij** [comment]
This is fixed and will be included in 1.6.1, thanks for the help.

**Comment by brettmhoffman** [comment]
Confirmed the fix as well. Thanks so much!

**Comment by barrykooij** [comment]
Thanks for letting me know!
