### ISSUE TITLE
Conflict with WPML plugin

### ISSUE THREAD

**Issue by barrykooij** [download-monitor/download-monitor#223]
I just tested the latest version of Download Monitor with my WP 4.1 installation running WPML for multi-language purposes.
You can select the add download button, light box opens but after that nothing happens. No way to insert a shortcode for a download.

https://wordpress.org/support/topic/conflict-with-wpml-plugin

**Comment by rootl** [comment]
Greetings. I have this exact problem using Download Monitor version 1.6.2 - it appears to conflict with Custom Content Type Manager (CCTM) custom fields. No way to insert shortcode, no way to insert or upload a file.   

Note: version 1.5.1 works perfectly with CCTM and other plugins on my site.

**Comment by barrykooij** [comment]
@rootl What is your setup in CCTM? What meta fields have you added to your post?

**Comment by barrykooij** [comment]
I was able to reproduce this and the error lies in WPML. Their main.js script triggers the following error Uncaught ReferenceError: ajaxurl is not defined. This is causing a JavaScript error that. Please report this to WPML and hope that they fix it. I'm sorry but I can't do anything about this.

@rootl If the CCTM conflict still exist please open a new issue.
