### ISSUE TITLE
WP Super Cache purges complete cache on download change.

### ISSUE THREAD

**Issue by barrykooij** [download-monitor/download-monitor#225]
Now I'm pasting the report from the supoprt of a hosting provider. They have found a problem between DLM and the WP-super-cache plugin. We had problems with DLM being extremely slow, this seems to be a possible cause

When the Download Monitor "Add File" button is clicked, WordPress
considers this an update to the post represented by the download. That
triggers the WP Super Cache function "wp_cache_post_edit" in
"/wp-content/plugins/wp-super-cache/wp-cache-phase2.php".

That function calls "wp_cache_post_change( $post_id )", which then calls
"wp_cache_post_id_gc( $siteurl, $post_id )".

That function is supposed to just delete the cached file directory ( a
few files) for the post being edited. It does that by calling:

$dir = get_current_url_supercache_dir( $post_id );
[...]
prune_super_cache( $dir, true, true );

In this case, "$dir" is supposed to be the cache directory of the post
being edited, because "get_current_url_supercache_dir()" is supposed to
return the root directory at
"/wp-content/cache/supercache/www.example.com/permalink-slug"
(where "permalink-slug" is the unique post directory).

But here's the problem: it appears that get_current_url_supercache_dir
doesn't find a permalink for the new Download Monitor post. Instead, it
simply returns $dir as the top level of the supercache directory:
"/wp-content/cache/supercache/www.example.com/". That gets
passed to prune_super_cache, which then "prunes" every cached file on
the entire site, not just the ones for the post being "edited".

**Comment by jboursaw** [comment]
Thank you for posting about this, as I'm having the same exact issue. I've tried different cache plugins (WP Fastest and ZenCache), and they work fine with Download Monitor but have other issues, so I keep going back to WP Super Cache. 

Has there been a resolution to the Download Monitor/WP Super Cache conflict?

**Comment by jboursaw** [comment]
Anything further on this, Download Monitor People? Would love to have this resolved in the next update.

**Comment by barrykooij** [comment]
@jboursaw sorry for the silence from my side. Looking into this for 1.8.0

**Comment by jboursaw** [comment]
Thank you so much, Barry! Fixing that cache issue would make my life way easier. :-) 

Also, I get about a hundred downloads on my files every day. I'm 310% positive that I don't have that many premium members downloading my movie reviews, so there must be a glitch somewhere in the Download Monitor system. We blocked off all the search engines, so I know it's not that. 

I know WooCommerce had a similar glitch that was recently fixed. 

And while I'm making my wish list, it would be great if the notifications said WHO downloaded the files. 

Thank you! 

Jane

**Comment by barrykooij** [comment]
@jboursaw Please open a new issue here on GitHub for that issue so we can try to solve that there :)

**Comment by barrykooij** [comment]
I looked into this today and I'm afraid the problem is in the WP Super Cache plugin. I've created a detailed report at their repository with the steps to reproduce this error. The issue can be found here: https://github.com/Automattic/wp-super-cache/issues/45

I hope they'll fix this soon.

**Comment by jboursaw** [comment]
Ok, thank you so much. I hope they can resolve it.
