### ISSUE TITLE
feature request: multiple files downloads

### ISSUE THREAD

**Issue by maphy-psd** [download-monitor/download-monitor#226]
Hi!

I think a support for multiple files downloads would be useful. Maybe with a zip file creation after the upload. For now, it's only possible to insert/upload some files in the explanation text field with the wordpress built-in Upload, but this files aren't stored in the dlm_upload folder.

Thank you!

**Comment by barrykooij** [comment]
Why wouldn't you want to create the zip file on your computer yourself?

**Comment by maphy-psd** [comment]
this is the way i do it now..but for multiple uploads it would be a nice feature. You can upload multiple files and those files will be downloaded as a zip.

**Comment by barrykooij** [comment]
It's an interesting that has been added to the extension board. I don't think this is something that many people would use but I can definitely see you mean.

Closing this for now, I'd be happy to post an update here once there's news of the extension.
