### ISSUE TITLE
add some mime types has no efect on DLM

### ISSUE THREAD

**Issue by maphy-psd** [download-monitor/download-monitor#227]
Hi!

I add some mime types with the help of your link: [Change WordPress Upload Mime Types](http://www.paulund.co.uk/change-wordpress-upload-mime-types)

After that, i can upload with the wordpress built-in uploading tool. When i upload the same file with the DLM Uploading tool, i get an error, that this filetype isn't allowed. When i add the filetype with the given [plugin](http://wordpress.org/plugins/manage-upload-types/) everything is ok.

Greets

**Comment by barrykooij** [comment]
So when you set them with the plugin, you can upload them in DLM?

**Comment by maphy-psd** [comment]
yes, then i can upload with DLM.

**Comment by barrykooij** [comment]
So, you're probably not adding them correctly when you custom code it. I can't provide custom code support, sorry.

**Comment by maphy-psd** [comment]
I used the link from your wiki..in my case:
```
add_filter('upload_mimes','add_custom_mime_types');
	function add_custom_mime_types($mimes){
		return array_merge($mimes,array (
			'tex' => 'application/x-tex',
		));
	}
```
The wordpress built-in uploading works, but not the DLM. With the plugin it works..closed.
