### ISSUE TITLE
Download Title = ID?

### ISSUE THREAD

**Issue by Lukbec** [download-monitor/download-monitor#231]
Hey,

i need the Download ID for the Shortcode "echo do_shortcode('[download id="'.$id.'"]');"
i have a Dropdown Menu for the Download list (costum fields).
how can i with the title the id to find out?

**Comment by barrykooij** [comment]
What you're looking for here is custom development and unfortunately I can't help you with that. I suggest you ask your question somewhere created for these kind of questions like wordpress.stackexchange.com or consider hiring a developer.

**Comment by salarrue** [comment]
Hello I am using this plugin in combination to

http://www.advancedcustomfields.com/

and

https://wordpress.org/plugins/email-before-download/

And here is the code that is working for me

```
<?php $download = get_field( "descarga" ); ?>
<div id="div1"></div>
<div id="div2" style="display:none"><?php echo do_shortcode('[email-download download_id="'.$download->ID.'" contact_form_id="600"]'); ?><a href="#">cerrar</a></div>
```


get_field( "descarga" ) is the custom field I generated to identify the item to download, then download_id="'.$download->ID.'" is were it gets the ID

I hope it helps.

**Comment by Lukbec** [comment]
@salarrue Thanks! It Works!
