### ISSUE TITLE
Problem with docx files

### ISSUE THREAD

**Issue by barrykooij** [download-monitor/download-monitor#234]
There appears to be a problem with download docx files. Microsoft Office opens a convert popup after opening the download file. Need to test this on Windows.

**Comment by G-W-github** [comment]
Hello,

has a solution for this? Has it to do with the last update?

Greetings

**Comment by barrykooij** [comment]
I still need to test this. Will do soon.

**Comment by barrykooij** [comment]
Just tested this, works fine here.

**Comment by barrykooij** [comment]
Just had this tested at another Windows computer an there is indeed a 'protected view message' but this is because Windows detects the file is downloaded from the internet. They do this to protect you. Closing this.

**Comment by G-W-github** [comment]
Hello indeed the problem seems solved. The shown vester was no safety warning but demand a conversion. I had this on Windows as well as Mac. But now it seems indeed solved ...

Thanks for figuring out.

Greetings
