### ISSUE TITLE
Update notification for logged in users

### ISSUE THREAD

**Issue by TheZoker** [download-monitor/download-monitor#236]
Hi there,

Is there a possibility to send a notification email to all logged in users, who downloaded a file, if there is a new version of that file uploaded?

So something like:
"A new version of file xyz is available. Follow this link to download the update"

Thank you

**Comment by barrykooij** [comment]
There isn't. Closest thing to what you want is you'd use one of the download lock extensions from https://www.download-monitor.com/extensions/ you can collect the email addresses and email them yourself.

**Comment by TheZoker** [comment]
Can you may add such a feature?

**Comment by barrykooij** [comment]
Maybe in an extension but this will not get into core.

**Comment by TheZoker** [comment]
Would be awesome!
