### ISSUE TITLE
Template does not work

### ISSUE THREAD

**Issue by TheZoker** [download-monitor/download-monitor#247]
Hi there,

I use this shortcode, but the template is still the default:
[download id="246" template=content-download-box]

I also tried [download id="246" template=content-download-box.php]

I would really like to create my own template (called custom-download.php placed in "download-monitor" folder in child theme) but does not work either....

**Comment by barrykooij** [comment]
@TheZoker Sorry for the delayed reply but did you try with: ```[download id="246" template="box"]``` because that's how this template is loaded.

**Comment by barrykooij** [comment]
Moving this to future milestone because I suspect this to be incorrect usage of shortcode.

**Comment by TheZoker** [comment]
I tried to use it this way:
`[download id="246" template=content-download-box.php]`
or 
`[download id="246" template=content-download-box]`

both do not work :/

**Comment by barrykooij** [comment]
But did you try it like is suggested? This way: ```[download id="246" template="box"]```

**Comment by TheZoker** [comment]
Yes it does work and this change makes it more clear why:
https://github.com/download-monitor/download-monitor/wiki/Content-Templates/_compare/adab766eced8a4be5a84b0668d509f43d7f12cb0%5E...adab766eced8a4be5a84b0668d509f43d7f12cb0
