### ISSUE TITLE
Let users add downloads on front-end

### ISSUE THREAD

**Issue by alexanderahlsen** [download-monitor/download-monitor#249]
Hello,

I was wondering if there is a easy way to let the users add downloads on the front-page? Could we use UserPro to be able to display the post adding for downloads on the front page?

**Comment by barrykooij** [comment]
I've not worked with UserPro so I wouldn't know :) Please use the WP forum for support and GitHub for bug reports. https://wordpress.org/support/plugin/download-monitor
