### ISSUE TITLE
Download file date not saved on post publish

### ISSUE THREAD

**Issue by barrykooij** [download-monitor/download-monitor#251]
Hi, i'm using the plugin to have a list of available downloads ordered by "File date" value with a custom query.

The problem that i've noticed is about the "File date" value storing.
When i create a new download post, and i assign a past date to the "File date" value, after first publish of the post i get the current day as "File date" value and not the past one that i've selected through the date picker.
The past date is shown, but then the value used/stored is the current day.
If i go back to the post, and i click on update, without editing the "File date" value, i get the correct value that i've set before through the date picker.

Can you help me please?
Otherwise i need always to publish the post and then click another time on update post to ahve the correct "File date" value.

Thank you.

https://wordpress.org/support/topic/download-file-date-not-saved-on-post-publish?replies=1

**Comment by barrykooij** [comment]
Should be fixed by c00580f2b7fa978cbd011aa2cb474bb296209817

**Comment by nixonmedia** [comment]
@barrykooij - I'm experiencing the same issue:
https://wordpress.org/support/topic/acf-date-picker-being-hijacked
https://www.dropbox.com/s/pvy4qjkuzj6bc9a/Screenshot%202015-11-05%2010.03.01.png?dl=0

I'm running v1.9.0 - Anything else I should try?
