### ISSUE TITLE
Chromium downloads custom extension as bin

### ISSUE THREAD

**Issue by huseyinkozan** [download-monitor/download-monitor#254]
I have a file with extension *.ekg. When I try to donwload with firefox file extension is correct, but not with chromium. *.ekg file is a binary file.

**Comment by barrykooij** [comment]
Just tested this with a dummy ```.ekg``` file and I can't reproduce this. Have you got the "Redirect to file" option at the download checked?

**Comment by huseyinkozan** [comment]
Redirect to file is not checked. I tried check stuation but the result was same. 

Here the link = http://infron.com.tr/indir/ornek_kayit-ekg/

All Options at the right are not checked. The file is added like this;
> /home/_some_user_/public_html/_some_dir_/Ornek_Kayit.ekg.

**Comment by barrykooij** [comment]
@huseyinkozan are you on apache or nginx?

**Comment by huseyinkozan** [comment]
This says apache :
toolbar.netcraft.com/site_report?url=http://www.infron.com.tr

2015-03-19 21:10 GMT+02:00 Barry Kooij <notifications@github.com>:

> @huseyinkozan <https://github.com/huseyinkozan> are you on apache or
> nginx?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/download-monitor/download-monitor/issues/254#issuecomment-83720860>
> .
>



-- 
Hüseyin Kozan

**Comment by barrykooij** [comment]
I've tested this on Apache as well and it appears to work fine. I downloaded your .ekg file but I don't know what content it suppose to have so I can't validate it. 

1. Did you install any Chrome extensions? Are you able to test to download the file on a different computer?
2. In what browser did you upload the file?

Moving this to the next milestone for now.

**Comment by huseyinkozan** [comment]
2015-03-20 21:23 GMT+02:00 Barry Kooij <notifications@github.com>:

> Did you install any Chrome extensions? Are you able to test to download
> the file on a different computer?


​I have Adblock Plus installed and some others not related to content
(tweetdeck, etc).​


> In what browser did you upload the file?


​I uploaded the file by filezilla, and paste the link.

Thanks.​



-- 
Hüseyin Kozan

**Comment by barrykooij** [comment]
Could you try and upload the file via the WordPress admin and see if that works?

**Comment by huseyinkozan** [comment]
It works. Thanks.
