### ISSUE TITLE
Ability to hide downloads from being searchable (DLM page add-on or otherwise)

### ISSUE THREAD

**Issue by tjdurden** [download-monitor/download-monitor#255]
I've use DLM to manage a number of files, the vast majority are contained within a 'resources' section. However, there are other downloads that I want to track, but don't want to be searchable within that resources section. 

Wondering if there's a way to do this, or you could look at adding it in please? (Thinking as it's a custom post type, there might be a way to set a single post as not searchable).

Many thanks

**Comment by barrykooij** [comment]
Do you mean in the Page Addon extension?

**Comment by tjdurden** [comment]
Yeah - it'd be great to be able to exclude a download from the DLM page addon search.

**Comment by barrykooij** [comment]
Sorry for my delayed reply. Add the following snippet to your theme's functions.php and enter the download ID's you want to exclude in the `$exclude_ids` array.

https://gist.github.com/barrykooij/fb3164914f624b38176b

**Comment by tjdurden** [comment]
Awesome, thanks Barry. 

Wondering if it might be a nice feature to make this possible within the WP admin screen (e.g. Downloads -> Edit Download -> 'Hide from DLM Page Add-on Search') if the DLM Page Addon is installed.

Either way, thanks for getting back and for providing the snippet, much appreciated.
