### ISSUE TITLE
Insert download button disappeared in Ninja Form's TinyMce editor

### ISSUE THREAD

**Issue by barrykooij** [download-monitor/download-monitor#256]
Thank you for this very useful plugin.
We used to add downloads inside Ninja Forms plugin (2.8.13, latest) success pages.
The "Insert Download" button above TinyMCE editor disappeared in this context (it displays on articles and pages posts) after upgrading DM to 1.6.3
I tried deactivating and reactivating all plugins one by one with no success.
I run WP 4.1.1
Could you please point me the DM plugin file to modify to have the "Insert Download" button appearing in any context ?

https://wordpress.org/support/topic/insert-download-button-disappeared-in-ninja-forms-tinymce-editor?replies=2

**Comment by Sophabed** [comment]
Hello,
I have switched to older Download monitor version to see when the issue appeared:
1.5.1 was working fine, 1.6.0 wasn't.
Bests
