### ISSUE TITLE
DLM Page Addon: Support commenting

### ISSUE THREAD

**Issue by tjdurden** [download-monitor/download-monitor#259]
Wondering if there's a way to add comments on downloads (download-info page)?

**Comment by barrykooij** [comment]
Not by default, you can override the templates tho to include them yourself. You can read more on this here: https://github.com/download-monitor/download-monitor/wiki/Page-addon#template-overrides

**Comment by tjdurden** [comment]
Please re-open. Overriding the template does not (appear to) allow comments to be added to a single download-info page.

I've tried adding 'comments_template()' to the 'content-download-page-singe.php' template, nothing appeared initially. As everything hangs off the page where the [download_page] shortcode has been applied, I tried enabling comments on that page, which enabled comments across all download-info pages.

My hunch is that the custom post type used for each download needs to support comments first. Beyond that, the mechanism used to display content on the download-info page for a specific download (custom post type) may need to be updated to pull in comments raised against that custom post type.

Please can you confirm my understanding. Either way, it feels like DLM Page Addon is unlikely (in its current format) to be able to support comments?
