### ISSUE TITLE
Broken Download Links when using Page Addon

### ISSUE THREAD

**Issue by SollertiaStation** [download-monitor/download-monitor#264]
For some reason, the download links shown using the "download_page" shortcode have broken. The php error log reports a problem with the $dlm_download object. I've included the error below:

 Call to a member function get_file_versions() on a non-object in /*sanitised_path*/wp-content/plugins/dlm-page-addon/templates/content-download-pa-single.php on line 8

The line in it refers to the is $dlm_download object, which I'm guessing is returning null. The download button shown reports the URL for the download as "php%20$dlm_download-the_download_link();"

You can view the error in action on our live site "www.sollertiastation.org/downloads/"

I require an urgent fix for this, if possible. 

Thanks in advance.

Shaun.

**Comment by barrykooij** [comment]
Hey Shaun,

This is fixed in the latest Page Addon release. Please update and let me know if the problem persists.

Kind Regards,

Barry Kooij

**Comment by SollertiaStation** [comment]
Hi there,

Yes the update works, however I am a little chuffed that what was advertised as a "free" addon is now in fact a paid addon. Can you confirm this, and what you have planned to do in future with regards to existing free licences?

Kind regards,

Shaun
