### ISSUE TITLE
[Improvement] Make it easier to use Search Form across templates

### ISSUE THREAD

**Issue by tjdurden** [download-monitor/download-monitor#267]
This applies to the DLM Page Addon plugin.

I spent some time this evening trying to update templates to add the Search form so users can search again after being displayed content on various DLM Page Addon pages (e.g. above a list of search results, or category list etc).

However, when embedded in a page at a different URL (not an endpoint of the base URL), search fails, and simply reloads the page.

I was wondering if this could be made easier, making the search form easier to re-use in the templates please?

**Comment by barrykooij** [comment]
Hey there,

This is a Page Addon Extension issue isn't it? If so, you're entitled to premium email support. Please send me an email via https://www.download-monitor.com/contact/

Kind Regards,

Barry Kooij
