### ISSUE TITLE
Question: How do I customise the (returned) Search results page (only)?

### ISSUE THREAD

**Issue by tjdurden** [download-monitor/download-monitor#268]
When search results are returned, the 'download-list.php' template gets used. I'd like to customise this so the search results page (for results found) is consistent with the 'no-downloads-found.php' template.

What's the best way to approach this?

**Comment by barrykooij** [comment]
Hey there,

This looks like a Page Addon Extension issue isn't it? If so, you're entitled to premium email support. Please send me an email via https://www.download-monitor.com/contact/

Kind Regards,

Barry Kooij
