### ISSUE TITLE
[Feature Request] Only increment downloads count for unique IPs

### ISSUE THREAD

**Issue by mdmower** [download-monitor/download-monitor#269]
Some users create tens of connections at a time to files I host. This may be due to their fancy (terrible) download managers or a proxy server. The download counts on my files are then artificially inflated and unreliable.

It would be nice if an option existed to only increment the download count on a specific file version if the IP address is unique from previous downloaders.

While not a perfect solution, it would be significantly more realistic that what I'm seeing now.

**Comment by mdmower** [comment]
I've started work on this feature request at: [mdmower/download-monitor: dev branch](https://github.com/mdmower/download-monitor/commits/dev)

As of this writing, the relevant commit is completely untested and will probably break the world, but it should give an indication of what I hope to achieve. I'll report back when I have something more final.

**Comment by mdmower** [comment]
See [pull request 276](https://github.com/download-monitor/download-monitor/pull/276).

**Comment by barrykooij** [comment]
Fixed in PR.
