### ISSUE TITLE
Unable to download from mobile WebKit-based clients

### ISSUE THREAD

**Issue by mdmower** [download-monitor/download-monitor#273]
Web server: Ubuntu 14.04.1
Apache 2.4.7, PHP 5.5.9, MySQL 5.5.43
WordPress 4.1.4
Download Monitor 1.7.2
Sample page with download links: http://android.cmphys.com/twrp-m7/
"Redirect to file" is enabled for all of my downloads

I am unable to download files from my site when touching links from either AOSP browser or Chrome on Android.  On the mobile device, I get notification "&lt;Untitled&gt; Download unsuccessful".

Downloads works properly in Firefox Mobile.

I have a mobile theme plugin (WPtouch), but disabling the plugin does not remedy this issue. In fact, on my Nexus 7 tablet, the normal site theme is served instead of the mobile theme, and the issue persists there.

I have hotlinking disabled in Download Monitor settings, but changing this setting does not remedy the issue.

Apache does not log any errors in error.log. For Chrome, the unsuccessful download attempt is logged in access.log as:

    2600:1014:b123:8f47:1673:6d0f:71f4:7400 - - [29/Apr/2015:13:07:56 -0500] "GET /download/1250/?version=2-8-6-4 HTTP/1.1" 302 421 "-" "Mozilla/5.0 (Linux; Android 5.0; XT1096 Build/LXE22.46-11) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.109 Mobile Safari/537.36"

For Firefox Mobile, the successful download attempt is logged as:

    2600:1014:b123:8f47:1673:6d0f:71f4:7400 - - [29/Apr/2015:13:14:33 -0500] "GET /wp-content/uploads/android/m7univ/twrp-2.8.6.4-m7univ.img HTTP/1.1" 200 12820732 "http://android.cmphys.com/twrp-m7/" "Mozilla/5.0 (Android; Mobile; rv:37.0) Gecko/37.0 Firefox/37.0"

If instead of simply touching the link in Chrome, I long-press and select "Open link in new tab", the download is successful.

**Comment by mdmower** [comment]
Could this be due to use of HTTP status code 302 to perform the redirect? Perhaps Chrome handles it differently? Based on [wikipedia's http status codes](http://en.wikipedia.org/wiki/List_of_HTTP_status_codes) article, it sounds like 302 is deprecated in favor of 303 and 307 for HTTP/1.1.

**Comment by mdmower** [comment]
To make sure this wasn't a theme related problem, I tested on a completely stock WordPress site, using a standard WordPress theme. Visiting [wptest.cmphys.com](http://wptest.cmphys.com/) and attempting to download a file from Chrome on Android results in the same failed download.

Another detail: this issue occurs regardless of whether mod_xsendfile is installed on the server.

**Comment by mdmower** [comment]
I probably should have tested this earlier, but it seems this is a compatibility issue with CloudFlare. When I put [wptest.cmphys.com](http://wptest.cmphys.com) in bypass mode (i.e. don't go through CloudFlare), the downloads redirect fine in mobile Chrome. I'll hop over to their forums and see if I can get some hints about whether there are additional apache headers that could help this.

**Comment by mdmower** [comment]
Ok, I think I've resolved this on CloudFlare's end. It appears to be an issue with CloudFlare's [Browser Integrity Check](https://support.cloudflare.com/hc/en-us/articles/200170086-What-does-the-Browser-Integrity-Check-do-). In case this issue is dredged up by anyone else with the same issue, the workaround is below:

1. Ensure all downloads handled by download-monitor are under some common path (can be in differing subdirs of this path though). For example: `wp-content/uploads/dlm`
2. On CloudFlare, select your domain and create a [page rule](https://support.cloudflare.com/hc/en-us/articles/200172336-How-do-I-create-a-Page-Rule-). Match downloads with a pattern and turn-off "Browser Integrity Check". Example pattern: `mydomain.com/wp-content/uploads/dlm/*`

**Comment by barrykooij** [comment]
That's good to know, thanks for figuring that out.
