### ISSUE TITLE
Cannot change how the download is displayed on the website

### ISSUE THREAD

**Issue by SimonneBosiers** [download-monitor/download-monitor#275]
The standard template selection doesn't not get saved / activated. The console says that the settings are saved, but they not take effect. Looking at the files on the server, no file has been updated. Using the German language version of the plugin.
Thank you for your help, Simonne

![download monitor screenshot 1](https://cloud.githubusercontent.com/assets/10348765/7436487/71cf08fa-f04e-11e4-8940-55b9d8d0a896.png)
![download monitor screenshot 2](https://cloud.githubusercontent.com/assets/10348765/7436486/71a49aac-f04e-11e4-8b08-173286a741b6.png)
![download monitor screenshot 3](https://cloud.githubusercontent.com/assets/10348765/7436485/719e5656-f04e-11e4-924f-d939c3ef6afc.png)

**Comment by mdmower** [comment]
It looks like there might be an issue with the German template: [download-monitor-de_DE.po Line 985](https://github.com/download-monitor/download-monitor/blob/master/languages/download-monitor-de_DE.po#L985). Both templates (with and without count indicator) are on the same line. You might be able to help the developer with translations at [transifex - download-monitor](https://www.transifex.com/projects/p/download-monitor/).

You say you want just the filename though. For this, you would need to create a custom template. You can copy the `content-download-filename.php` template in `wp-content/plugins/download-monitor/templates` to a new template (e.g. `content-download-filename-only.php`) and edit it to _remove_ these lines to achieve your goal:

    (<?php printf( _n( '1 download', '%d downloads', $dlm_download->get_the_download_count(), 'download-monitor' ), $dlm_download->get_the_download_count() ) ?>
    )

**Comment by SimonneBosiers** [comment]
Dear Matt, thanks very much for looking into this issue. I changed the language of my WP from German to English, deleted the plugin and installed it again. No difference, again, none of the changes to the settings take effect. None of the plugin´s files get updated when changing the settings through the backend interface, so that I think says enough. Do you have an idea where that could be? I am not a WP programmer at all, I used to program a lot a long time ago, so I do understand logic and can find my way through code. Thanks again for your spontaneous help, Simonne

**Comment by mdmower** [comment]
Hmm, this is strange. I can definitely change templates and it takes effect immediately.

Perhaps you could report what kind of hosting environment you're using? For example: I'm using Ubuntu 14.04, Apache 2.4, PHP 5.5, MySQL 5.5, WordPress 4.1. If possible check your server's error logs after attempting to change settings unsuccessfully (for Apache: `/var/log/apache2/error.log`).

**Comment by barrykooij** [comment]
hey @SimonneBosiers any update on this?

**Comment by barrykooij** [comment]
Closing this due inactivity, feel free to reopen is issue still exists.
