### ISSUE TITLE
Download page 

### ISSUE THREAD

**Issue by bryan-farris** [download-monitor/download-monitor#288]
I'm using the [download_page] shortcode to display the available downloads.  Everything looks great.  

However, when I click on any of the links, a URL of:

https://domain.com/member-dashboard/downloads/download-info/download-file-slug/

tries to open.  This page never resolves or redirects anywhere.  If I try visiting any of the individual download URLs: https://domain.com/download/596/, this link resolves.  

Can anyone point me in the right direction here? I'm not sure why the links are outputting/displaying differently.

Thanks

**Comment by barrykooij** [comment]
Hey there,

This is a Page Addon Extension issue isn't it? If so, you're entitled to premium email support. Please send me an email via https://www.download-monitor.com/contact/

Kind Regards,

Barry Kooij
