### ISSUE TITLE
Massive Amounts of Downloads

### ISSUE THREAD

**Issue by jboursaw** [download-monitor/download-monitor#294]
I get about a hundred downloads on my files every day. I'm 310% positive that I don't have that many premium members downloading my movie reviews, so there must be a glitch somewhere in the Download Monitor system. We blocked off all the search engines, so I know it's not that.

I know WooCommerce had a similar glitch that was recently fixed.

Thanks for any help or future updates to resolve the issue.

**Comment by barrykooij** [comment]
Are these downloads marked 'Members Only'?

**Comment by jboursaw** [comment]
Well, the particular section of my site that utilizes Download Monitor is for paying Premium Members only. However, the notifications I get via email do not specify any sort of Members Only notation.

**Comment by jboursaw** [comment]
Today there were 310 downloads, and I'm quite sure those weren't all "real" downloads.

**Comment by barrykooij** [comment]
The thing is that the downloads itself must be protected and not the page they're listed on. If you edit a download in the backend there will be a checkbox in the right side of the screen saying 'Members Only'. Checking this (and saving your download) will restrict access to the downloads to logged in users.

**Comment by jboursaw** [comment]
Ah - ok, thanks so much. I'll make sure the Members Only box is checked.

**Comment by barrykooij** [comment]
Great! :+1:
