### ISSUE TITLE
Using Mailchimp extension

### ISSUE THREAD

**Issue by Perezmarc** [download-monitor/download-monitor#301]
Hello, 
I bought the Mailchimp extension and activated it already. But now I fail to find the checkbox on the right of a download, under download options. I only can see the 3 checkbox I could before installing mailchimp extension.
I do have the official mailchimp plugin installed.

Thanks!

**Comment by barrykooij** [comment]
Please reply to your purchase email or contact us via https://www.download-monitor.com/contact/ so I can help you via email.
