### ISSUE TITLE
Version 1.8.0 breaks downloads. WordPress 4.2.2

### ISSUE THREAD

**Issue by cyberfunk** [download-monitor/download-monitor#307]
First off thanks for this excellent plugin. I recently updated to version 1.8.0 and it broke all download links. I get a message that "headers have already been sent..." at the top of a very long WordPress error page which also generates a spinning beach ball in Firefox for Mac. I immediately deleted version 1.8.0 and reverted to version 1.7.2 and everything is working again :-O Whew! Has anyone else reported this error? I'll stick with 1.7.2 for the time being. Thanks again for providing such an essential plugin.

**Comment by barrykooij** [comment]
Can't confirm this and this is the only report I've had, must be a conflict with a plugin or theme.
