### ISSUE TITLE
wp_reset_postdata breaks my loop

### ISSUE THREAD

**Issue by createdwithlove** [download-monitor/download-monitor#312]
On my website I use a custom WP_Query collecting and outputting a parent-page and its child-pages to achive a "onepage" Layout:

```php

$posts = array();
$posts[] = $post->ID;

$args    = array(
	'posts_per_page'   => -1,
	'orderby'          => 'menu_order',
	'order'            => 'ASC',
	'post_type'        => 'page',
	'post_parent'      => $post->ID,
	'post_status'      => 'publish',
	'suppress_filters' => true
);

$postlist = get_posts( $args );

foreach ( $postlist as $post ) {
	$posts[] += $post->ID;
}

$query = new WP_Query( array(
	'post_type'   => 'page',
	'orderby'     => 'menu_order',
	'order'       => 'ASC',
	'post__in' => $posts,
	'$showposts'  => - 1
) );

while ( $query->have_posts() ) : $query->the_post();
	get_template_part( 'loops/loop', 'standard' );
	var_dump( $post );
endwhile;
```

On one of those child-pages I use a Shortcode `[download id="1418" template="fancy"]` to output a downloadlink.

Saddly the `wp_reset_postdata();`in `class-dlm-shortcodes.php` resets my custom query and some following meta queries (with the Advanced Custom Fields plugin) now use the $post->ID of the parent page.

Maybe resetting postdata can be omitted?

**Comment by barrykooij** [comment]
Unfortunately we'll have to do this because we create a new WP_Query object. You could avoid this conflict by using `get_posts` or do something 'hacky' like storing the original post ID in a temp variable and setting it back to `$post` after your custom code.

Sorry about this but this unfortunately is WordPress's architecture.
