### ISSUE TITLE
[Feature Request] Limit downloads per user

### ISSUE THREAD

**Issue by iannuttall** [download-monitor/download-monitor#315]
A lot of membership sites might have a use for limiting the downloads per user (like 1 per day, 10 per month etc) to try and encourage signups to a higher plan.

Would be great to see something like this (even as a paid extension) that would work with bridges like the Restrict Content Pro one (https://pippinsplugins.com/restrict-content-pro-download-monitor-bridge/). :)

**Comment by barrykooij** [comment]
This should be possible with our Advanced Access Manager: https://www.download-monitor.com/extensions/advanced-access-manager/
