### ISSUE TITLE
Glitch with WP SuperCache

### ISSUE THREAD

**Issue by jboursaw** [download-monitor/download-monitor#316]
There's a couple of glitches with Download Monitor and WP SuperCache.

1) When you go to "add a file" when creating a download, the system cycles through the entire cache, which causes the system to crash. I believe this one has been fixed, because I don't have to wait forever for the file to be added anymore. 

2) When you go to "publish" a download, the same thing happens - I believe it cycles through the cache, which takes forever and causes the system to crash. This one is still an issue.

**Comment by barrykooij** [comment]
Hey @jboursaw,

Sorry to hear there's still no fix for this. I've created an issue on the WPSC repository here: https://github.com/Automattic/wp-super-cache/issues/45
Maybe you could leave a reply there as well?

**Comment by donnchawp** [comment]
@barrykooij I closed your ticket with https://github.com/Automattic/wp-super-cache/pull/420 which fixed the problem in my testing. If you use WP Super Cache you can grab master to test it.

**Comment by barrykooij** [comment]
@donnchawp Thank you!
