### ISSUE TITLE
Problem with handler class dlm download handler

### ISSUE THREAD

**Issue by christianoviedo** [download-monitor/download-monitor#318]
After lots of testing (reseting permalinks, and changing templates), I found a problem in function handler.

$wp->query_vars have this data:
Array ( [page] => /674 [name] => downloads)

So I had to add this code into handler function:
		if ($wp->query_vars['name']==$this->endpoint) {
			$wp->query_vars[ $this->endpoint ] = $wp->query_vars['page'];
		}

And it works.

**Comment by barrykooij** [comment]
Hey,
Could you please elaborate what wasn't working before and what lines you changed (or create a PR!). Also, what version of Download Monitor are you using?

**Comment by barrykooij** [comment]
Closing due inactivity. Please reopen if this is still an issue for you.
