### ISSUE TITLE
Display download log at front end

### ISSUE THREAD

**Issue by jamblo** [download-monitor/download-monitor#321]
Hi there

Looking at the potential for using your plugin to display recent downloaded plugins on the frontend, on a user profile page.

Essentially, each user would have their own profile page (protected by their WP login). When they visit the page, get_current_user() will be used to display their profile details.

What I'm wondering is if – using the users ID – we can query the Download Monitor logs and display the last two files the user has downloaded in his or her profile?

Is there a way of accessing the logs through a specific query? Is it a custom post type?

Thanks in advance,
James

**Comment by barrykooij** [comment]
Hey James,

This would be possible but the log is a custom table so you would need to query the custom table.

Kind Regards,

Barry Kooij
