### ISSUE TITLE
Wordpress - Blank screen after activation

### ISSUE THREAD

**Issue by Soullighter** [download-monitor/download-monitor#327]
I was manage to install this great plugin on my localhost, but when i want to install in on live site i just get blank page after click on "activate plugin" button. Also i'm unable to get inside wp-admin panel after this, so i'm forced to delete plugin manually and get thinks right, like it was before activation.

**Comment by barrykooij** [comment]
Please enable WP_DEBUG and create a new issue with the exact PHP errors you get.
