### ISSUE TITLE
HTML error in Download link since last plugin update

### ISSUE THREAD

**Issue by barrykooij** [download-monitor/download-monitor#328]
Looks like something went wrong during your last plugin update. Instead of outputting the actual download link in HTML, some broken shortcode is being returned. See screenhot. Could you have a look?

Report: https://wordpress.org/support/topic/html-error-in-download-link-since-last-plugin-update?replies=1

**Comment by barrykooij** [comment]
Report 2: https://wordpress.org/support/topic/outputting-broken-shortcode-instead-of-link?replies=1

**Comment by barrykooij** [comment]
This seems like a conflict caused by Tablepress. User changed double quotes to single quotes and this fixed the issue, which can't be caused by us because we don't care about what (or if) quotes are used.

**Comment by chrismccoy** [comment]
ive encountered this, not using tablepress though, just gravityforms, and the download monitor plugin, seems that it isnt rendering the 

    href="<?php $dlm_download->the_download_link(); ?>"

**Comment by barrykooij** [comment]
@chrismccoy very odd, that should simply echo the `$this->get_download_link();` Does this error persist with only Download Monitor active and a default theme like TwentySixteen selected?

**Comment by chrismccoy** [comment]
seems to work in 2016 theme, dont know what changed, the install has been the same, worked since i added the plugin on the site, only thing that recently changed was an update of wordpress, same theme, no actual changes plugins/themes wise.
