### ISSUE TITLE
Shortcode appears to override $post object

### ISSUE THREAD

**Issue by barrykooij** [download-monitor/download-monitor#330]
User report functions like `the_title()` aren't working anymore after a `do_shortcode()` of `[download]`.

**Comment by fakrulislam** [comment]
Will wait for the updates.

**Comment by barrykooij** [comment]
Just ran some tests and everything appears to work like it should. See my test result of doing a `get_the_title()`, `do_shortcode();` and finally another `get_title()`:

![image](https://cloud.githubusercontent.com/assets/2846594/11476235/e8651f74-9781-11e5-8335-27326987f516.png)

I suspect you're not properly setting up the WP post object, causing this issue. Please make sure you setup your WP post object with `the_post();` and that your custom code including `the_title();` are called inside `the_loop();`
