### ISSUE TITLE
Reuse of media frame appends to wrong textarea

### ISSUE THREAD

**Issue by kraftner** [download-monitor/download-monitor#333]
## Steps to reproduce

1. Create a Download with at least two versions
2. Add or change one of the URLs using the "Upload file" button. This works as intended.
3. Now click the "Upload file" button on any *other* Version and add a file. The new URL is appended to whatever version you did your first change to.

## The issue

I have identified the issue as being [the reuse of the media frame](https://github.com/download-monitor/download-monitor/blob/83c22d6d03e34d5a923dba4efa125d7dd6e810dc/assets/js/edit-download.js#L176-L180)

As no new media frame is created after the first call the values for [`$file_path_field` and `file_paths`](https://github.com/download-monitor/download-monitor/blob/83c22d6d03e34d5a923dba4efa125d7dd6e810dc/assets/js/edit-download.js#L171-L172) stay the same in [the select listener](https://github.com/download-monitor/download-monitor/blob/83c22d6d03e34d5a923dba4efa125d7dd6e810dc/assets/js/edit-download.js#L207-L222).

## Possible fix

A possible fix is to create a new media frame each time a button is clicked. I am not familiar enough with the media frame to know if cleaning up after old frames is needed, but maybe this makes sense:

    // If the media frame already exists, delete it.
    if ( dlm_upload_file_frame ) {
        dlm_upload_file_frame.close();
    }

instead of [the frame reuse](https://github.com/download-monitor/download-monitor/blob/83c22d6d03e34d5a923dba4efa125d7dd6e810dc/assets/js/edit-download.js#L176-L180).

I haven't tested this thoroughly but at first glance it seems to work properly for me.

**Comment by barrykooij** [comment]
Fixed at 7d001f1efd1942c1a505d5477ab291d0be15edef
