### ISSUE TITLE
flush_rewrite_rules should be at shutdown

### ISSUE THREAD

**Issue by sybrew** [download-monitor/download-monitor#338]
Hello!

I see that one of the flushes is initiated at the middle of the PHP script rather than shutdown.

This could cause plugin conflicts.

Please check out class-dlm-admin.php at line 450 and see if you can enqueue the flush at php shutdown.
WordPress has initiated an action at shutdown, aptly named shutdown.

e.g. 
```
//* @ __construct()
add_action( 'shutdown', array( $this, 'flush_rewrite_rules' ) );

public function flush_rewrite_rules() {
	
	//* Class var has been set to true at line 450
	if ( true === $this->initiate_flush ) {
		static $flushed = null;

		//* flushed already, short circuit
		if ( isset( $flushed ) )
			return;

		flush_rewrite_rules();
	
		$flushed = true;
	}
}
```
I hope this helps, thanks!

Related: https://wordpress.org/support/topic/tsf-creates-404-errors-in-download-monitor-links?replies=2#post-7973352

**Comment by barrykooij** [comment]
Fixed, thanks @sybrew
