### ISSUE TITLE
Add get_the_post_content and the_post_content to DLM_Download

### ISSUE THREAD

**Issue by barrykooij** [download-monitor/download-monitor#340]
I wanted to post this separately in case it got buried in my support request thread below!

It's confusing to have the usual "Post Content" section when adding/editing a download but have no way to access its value in download templates.

I'd like to request that the following code be added to /includes/class-dlm-download.php :

```
/**
     * get_the_post_content function.
     *
     * @access public
     * @return void
     */
    public function get_the_post_content() {
        return wpautop( do_shortcode( $this->post->post_content ) );
    }

    /**
     * the_post_content function.
     *
     * @access public
     * @return void
     */
    public function the_post_content() {
        echo $this->get_the_post_content();
    }
```

Thanks for your consideration! :)

https://wordpress.org/support/topic/feature-request-access-post_content-value-in-templates?replies=1

**Comment by PartPurple** [comment]
I [originally posted this](https://wordpress.org/support/topic/feature-request-access-post_content-value-in-templates/) on the Wordpress plugin page over a year ago. I have to manually re-add the code every time DM is updated in the WP repository. It's such a simple change...any way to get it worked in faster than 4.0.0? That's a looong way from the current version of 1.9.6!

**Comment by barrykooij** [comment]
The new Download object will have a `get_description()` method. This will return what you need.

Also, side note, the 4.0 version is the next version that will be released. There's a legacy version from a very long time ago that stopped at 3.3.x, so the 4.0 version will be a completely new version for everyone.
