### ISSUE TITLE
Log shows incorrect version if old version no longer exists

### ISSUE THREAD

**Issue by mdmower** [download-monitor/download-monitor#341]
If a specific version of a download is removed, the download log misreports the version of downloads associated with that version. Instead, the version displayed is the most recent version of a download available.

**Comment by barrykooij** [comment]
Let's look into this for 4.0. I'd like to give the logs a big update in 4.0

**Comment by barrykooij** [comment]
Merged in 1.9.3, thanks again @mdmower
