### ISSUE TITLE
Update coding to standard format of getting the path

### ISSUE THREAD

**Issue by johncrumpton** [download-monitor/download-monitor#342]
If the Wodpress folder layout is different to standard (for security hardening) then all download links break.

Error log:

`PHP Warning: fopen(): Filename cannot be empty in /var/www/vhosts/WEBSITE.org/httpdocs/wp-content/plugins/download-monitor/includes/class-dlm-download-handler.php on line 601`

This is due to the plugin not actually been coded using the standard format of getting the paths. The below link has the approved syntax for this and will need to update the code to accommodate for this please:

https://developer.wordpress.org/reference/functions/plugin_dir_path/

**Comment by barrykooij** [comment]
hey @johncrumpton, are you sure this is the case? Because that line uses the path you entered in your WP admin at the file version. If you've entered a URL we replace it with you ABSPATH with should be set correctly on non-default setups as well.

**Comment by johncrumpton** [comment]
hey Barry - I think we can close this, it must have been a server configuration issue as I've checked this again and it's working fine. Perhaps a caching issue? Thanks for looking into this though!

**Comment by barrykooij** [comment]
Thanks for letting me know @johncrumpton
