### ISSUE TITLE
category_include_children does not exclude child category

### ISSUE THREAD

**Issue by Pokerkoffer** [download-monitor/download-monitor#364]
Hi,
following category structure:
- CAT1
- \- CAT2
- -- CAT3

Download #dl_1 categories: CAT1,CAT2
Download #dl_2 categories: CAT1,CAT2,CAT3

Now i want to display downloads from CAT1 & CAT2 but NOT CAT3 ([... category="CAT1+CAT2"] which should output download #dl_1). I do this with setting category_include_children="false". Nevertheless, downloads from CAT3 (#dl_1 & #dl_2) are also displayed. 
Is this related because I have a category on level 3? Is this a bug or intended?

**Comment by barrykooij** [comment]
Sorry for my absurd late reply, I totally missed this issue! Please feel free to re-open this issue if this is still relevant.
