### ISSUE TITLE
Select file dialog doesn't open

### ISSUE THREAD

**Issue by orschiro** [download-monitor/download-monitor#366]
Dear all,

What a fantastic extension. Thank you so much!

I have one problem with it. Clicking on `Select File` doesn't open a window in my Chrome browser. 

Can anyone confirm that?

Thankfully,

~Robert

![image](https://cloud.githubusercontent.com/assets/170947/15492612/714f497e-217d-11e6-9386-eecb96cd65a5.png)

**Comment by orschiro** [comment]
Dear all, 

Can anyone confirm my problem?

Thankfully,

~Robert

**Comment by hchouhan** [comment]
Hey Robert, 
I would request you to create a support ticket at https://wordpress.org/support/plugin/download-monitor or you can also email us at "support @download-monitor.com" with details of your website.

**Comment by orschiro** [comment]
Dear @hchouhan,

Thanks for your reply!

I did as suggested and submitted a ticket on Wordpress [1]. :smiley: 

[1] https://wordpress.org/support/topic/select-file-dialog-doesnt-open?replies=1#post-8610645

**Comment by barrykooij** [comment]
As discussed on the WP forums, this is most likely a user specific theme issue.
