### ISSUE TITLE
Page Addon broken

### ISSUE THREAD

**Issue by vibrant08** [download-monitor/download-monitor#370]
Hi I upgraded to the new download monitor last night and had to do the DLM Importer. Then I purchased the Page Addon (D6D3-0555-4425-40FF) and the page won't work. http://www.cpcsschools.com/downloads/

Everything appears ok but click on a link, and it's broken. They are all broken, and the categories are broken too. Can you fix this ASAP?

Thanks,
Melinda

**Comment by barrykooij** [comment]
Hey Melinda,

Could you try re-saving the permalinks? You can do so by going to WordPress default settings > permalinks and click the 'Save changes' button. This usually resolves the issue.

For further questions please contact us via https://www.download-monitor.com/contact/

Kind Regards,
Barry Kooij

**Comment by vibrant08** [comment]
Yes that fixed it, thank you! Also there are tags at the top of the page I don’t want there, how can I remove those easily? http://www.cpcsschools.com/downloads/ 

 

Thanks,

Melinda

**Comment by barrykooij** [comment]
Please contact us via https://www.download-monitor.com/contact/ so we can help you via email. GitHub is used for bugs in the main plugin.
