### ISSUE TITLE
how to upload private file?

### ISSUE THREAD

**Issue by AoEiuV020** [download-monitor/download-monitor#377]
NOT "Members only"
怎么上传私有的文件？就像私有的post一样，
只有自己能下载，别的用户也不能下载，

**Comment by barrykooij** [comment]
Hey there,

We use github purely for bug reports. If you have a question or you're looking for other support, please create a topic on our free support forum: https://wordpress.org/support/plugin/download-monitor

Kind Regards,
Barry Kooij
