### ISSUE TITLE
PHP Warning: fopen class-dlm-download-handler.php on line 603

### ISSUE THREAD

**Issue by rahul964** [download-monitor/download-monitor#378]
Server details:
PHP version: 5.6.24
MySQL: 5.5.50
Wordpress Version: 4.6
Using: Cpanel
Server: OVH

**Error:**

> [17-Aug-2016 13:31:09 UTC] PHP Warning: fopen(http://www.mediafire.com/download/2dbdipwpqfgs6d9/SP_Flash_Tool_v5.1532_Win.zip): failed to open stream: HTTP request failed! in /home/xxxxxxxxxxx/public_html/wp-content/plugins/download-monitor/includes/class-dlm-download-handler.php on line 603

> [17-Aug-2016 13:31:09 UTC] PHP Warning: Cannot modify header information - headers already sent by (output started at /home/xxxxxxxxxxx/public_html/wp-content/plugins/download-monitor/includes/class-dlm-download-handler.php:603) in /home/xxxxxxxxxxx/public_html/wp-content/plugins/download-monitor/includes/class-dlm-download-handler.php on line 496

*** Im getting 20+ same error log daily for my website spflashtools.com. Im using your plugin on my 12 micro websites, and all of them are giving the same error.. even **tried on different server**.. but the error is same.

xxxxxxxxxxx = account username

**Comment by rahul964** [comment]
I have tried serving files from different host i.e https://dl-ssl.google.com//android/repository/latest_usb_driver_windows.zip which didnt cause any error.

BUT mediafire links are causing ERROR.

**Comment by barrykooij** [comment]
Hey Rahul,

Thanks for narrowing this down to the mediafire.com host. It appears that website is blocking us from reading the file directly from there server. Best thing to do is switch to another file hosting service but if you want to keep using mediafire, enable the option 'Redirect to file' for the mediafire downloads.

Kind Regards,

Barry Kooij

**Comment by kampiamodikuesto** [comment]
hi, i migrate a site with last version of download monitor installed. All files and db are the same but in the new hosting i get this error when i try to download a file.

“Warning: fopen(): Filename cannot be empty in /home/civitanavi/domains/civitanavi.com/public_html/wp-content/plugins/download-monitor/includes/class-dlm-download-handler.php on line 603” – (with wp debug true)

“ERR_INVALID_RESPONSE” (with wp debug false)

i ask my new hosting to see what’s the problem but they don’t want care about this “we don’t offer support on wp or other tools!!” so there is a way to know minimum hosting requirements for download monitor? there is a tool to check the compatibility?

**Comment by kampiamodikuesto** [comment]
hi, i try to debug this things width knit debug plugin and i add this string 
`d($file);` 
into

```
	public function readfile_chunked( $file, $retbytes = true, $range = false ) {
		$chunksize = 1 * ( 1024 * 1024 );
		$buffer    = '';
		$cnt       = 0;

		/* Debug wm*/
		d($file);
		/* END */

		$handle    = fopen( $file, 'r' );
```

nothing happen but the download works. Can someone explain me what happen?
