### ISSUE TITLE
PHP 7.0 Compatibility

### ISSUE THREAD

**Issue by sasserc** [download-monitor/download-monitor#379]
Love the plugin but migrating to php 7.0 soon at WPEngine and WPEngine php 7.0 compatibility plugin says download monitor is not compatible.  Plugin is located at https://wordpress.org/plugins/php-compatibility-checker/ 

**Here are errors from compatibility checker:**
## FOUND 3 ERRORS AFFECTING 3 LINES

 828 | ERROR | Deprecated PHP4 style constructor are not supported since PHP7
 845 | ERROR | Deprecated PHP4 style constructor are not supported since PHP7
## FOUND 2 ERRORS AFFECTING 2 LINES

 532 | ERROR | INI directive 'safe_mode' is deprecated from PHP 5.3 and forbidden from PHP 5.4.

**Comment by barrykooij** [comment]
Hey there,

When did you/WP Engine ran this test? We should have fixed these false-positives in our 1.9.5 release!

Cheers,
Barry
