### ISSUE TITLE
Members only doesn't work.

### ISSUE THREAD

**Issue by Alysko** [download-monitor/download-monitor#383]
Hi,
I have to add a conditionnal tag before doing do_shortcode because because "Members only" checkbox is ineffective.

**Comment by barrykooij** [comment]
Members only doesn't prevent the output of the download link. It does prevent he user from accessing/downloading the file. Please note that if you have `redirect to file` active, members only is unable to truly protect the file.

**Comment by barrykooij** [comment]
If you're having issues getting this to work. Please open a support ticket here https://wordpress.org/support/plugin/download-monitor
