### ISSUE TITLE
Wrong Download count

### ISSUE THREAD

**Issue by princecaspian** [download-monitor/download-monitor#387]
Hi
I used your plugin for a book launch. After two days, the download number got crazy. We have more than 12 000 downloads for less than 1 000 visitors which is not possible. 
I went to the log and noticed the same ip adress 12 000 times. Is there a way to remove all count from this specific iP so I can have a normal and real statistics of the downloads ? Is it normal ?
Thanks
regards,

**Comment by nijumohan** [comment]
Even I have the same problem. Not enough visitors but download numbers are way too high. Is there any way to clean this up?

**Comment by nijumohan** [comment]
This is happening again. There is any fix for this?

**Comment by barrykooij** [comment]
Looks like in both cases someone spammed your download URL. There's no build in way to clean up these log records at the moment, however you can do this manually in your database. By default the logging table we add is named `wpdb_download_log`. You should relatively easy be able to select the incorrect rows and delete them there.
