### ISSUE TITLE
Version List Template problem – only latest files getting downloaded

### ISSUE THREAD

**Issue by waqasq** [download-monitor/download-monitor#388]
When using the Version List template all the downloads are listed with their respective download versions and download count listed along …which is good. But the issue is that all the download link return the same latest download file when downloading instead of their actual file versions.

Please help me solve this issue as I am pretty sure that the intended purpose of this template is to serve the corresponding files instead of the erroneous latest file in the download list.

**Comment by barrykooij** [comment]
Hey there,

Sorry for my delayed reply. Could you please let me know what version of Download Monitor you're using?

Kind Regards,

Barry Kooij

**Comment by barrykooij** [comment]
Also please let me know what specific shortcode you're using.

**Comment by barrykooij** [comment]
No reply in almost a year. Closing.
