### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by thwolter** [download-monitor/download-monitor#391]
I'm trying to use the download monitor version 1.9.5 as it seems to be a great tool. I entered and published a new download (a small pdf file) however download link doesn't work (I receive the File not found message). 
#
I already tried with W3 Total Cache being switched off and error message remains. I'm using standard settings with empty IP Blacklist.

**Comment by barrykooij** [comment]
Hey,

Sorry for my delayed reply. Could you try re-saving the permalinks? You can do so by going to WordPress default settings > permalinks and click the 'Save changes' button. This usually resolves the issue. 

Please feel free to re-open this issue if that did not solve the issue.

Kind Regards,

Barry Kooij
