### ISSUE TITLE
Larger PDF's are not loaded in Chrome/IE/Safari but are working just fine in Firefox

### ISSUE THREAD

**Issue by Mule52** [download-monitor/download-monitor#393]
I am using Wordpress and Download Monitor to embed and view PDF files. I have four PDF files, two of them work successfully across all browsers, their sizes are 93kB and 20kB. The two that only work in Firefox but do not work in Chrome/IE/Safari are 273kB and 313kB. The issue is the PDF viewers just show a "loading" state, or a partially loaded state. The PDFs never render in these non-Firefox browsers. 

I have tried PDF Viewer and PDF Embedder as Wordprss PDF plugins, both yield similar results.

I want to use Download Monitor so I can keep unauthenticated users from accessing my PDF files via direct links. If there is another way to secure PDFs and other media so unauthenticated users cannot access them via direct links, then please share so I can test those solutions.

If I do not use Download Monitor and just access the PDF files via their direct links (direct links outside of Download Monitor and the dlm directory for my Wordpress site), then both PDF Viewer and PDF Embedder work successfully rendering all four of my PDFs, so size is no longer an issue.

Let me know if you need more info from me and/of if you think this is a bug. Thanks.

Wordpress version 4.7
Download Monitor version 1.9.5

Browser Versions:
Chrome 54
IE 11
Safari 10.0.1
Firefox 50

Tested on Mac, Windows 10 and Ubuntu 16 and 14, all with the same results.

**Comment by barrykooij** [comment]
Sorry for my delayed reply. Can you try enabling the "Redirect to file" option for the downloads, this will most likely fix this issue. Please re-open the issue if this doesn't solve the issue.
