### ISSUE TITLE
Function get_transient changed in 4.7.2

### ISSUE THREAD

**Issue by mods** [download-monitor/download-monitor#397]
Hi
the function get_transient() in wordpress 4.7.2 have changed.
The condition in function get_file_version_ids() not valid:
if ( false === ( $this->file_version_ids = get_transient( $transient_name ) ) ) 
Replace with :
if ( empty( $this->file_version_ids = get_transient( $transient_name ) ) )

**Comment by barrykooij** [comment]
Let me look into this. I sure hope they key backwards compatibility in this :)

**Comment by barrykooij** [comment]
@mods Do you have a link to a source or diff of this change? Official documentation still states return value on non-existence is false: https://codex.wordpress.org/Function_Reference/get_transient

**Comment by barrykooij** [comment]
Pushing this back because I can't find any sources on this and reporter isn't responding.

**Comment by mods** [comment]
Hi @barrykooij, I have no link or diff to be submitted.
I debug your plugin to solve the problem.

**Comment by barrykooij** [comment]
Hey,

I don't mean you need to solve the issue but I'd like to know where you read the `get_transient()` function has been changed. Because I can't find anything referring to this change.

Kind Regards,

Barry Kooij

**Comment by mods** [comment]
The function never return false if transient dont exist, but return an empty array.

**Comment by barrykooij** [comment]
I'm closing this because I can't replicate it. The official documentation also states:

> If the transient does not exist, does not have a value, or has expired, then get_transient will return false.
