### ISSUE TITLE
Downloads failing to complete

### ISSUE THREAD

**Issue by atdr** [download-monitor/download-monitor#398]
On our site downloads begin to load but fail before completing — Safari’s error message is “the network connection was lost”.

Previously downloads had failed to begin but recently they’ve started loading a few bytes before failing.

![](http://i.imgur.com/lhfDwFx.png)

Server is configured with nginx in front of Apache.

nginx error log:
```
2017/01/14 14:59:24 [error] 8138#0: *11595 upstream prematurely closed connection while reading upstream, client: 78.147.13.225, server: server-fps-staging, request: "GET /download/introduction-to-fps/ HTTP/1.1", upstream: "http://127.0.0.1:81/download/introduction-to-fps/", host: "www.futureproblemsolvinguk.org", referrer: "http://www.futureproblemsolvinguk.org/get-started/"
```

apache access log:
```
62.24.196.100 - - [14/Jan/2017:14:59:54 +0000] "GET /download/introduction-to-fps/ HTTP/1.0" 200 756
```

[cross-posted from [WordPress support forum](https://wordpress.org/support/topic/downloads-fail-to-complete/)]

**Comment by atdr** [comment]
Still having issues after the update to 1.9.6

**Comment by barrykooij** [comment]
This is most likely due to a server restriction on your server. You can work around this by enabling the *Redirect to file* option for your downloads.
