### ISSUE TITLE
Make logged data configurable

### ISSUE THREAD

**Issue by kraftner** [download-monitor/download-monitor#407]
Currently you can only choose between logging all data including possibly sensitive data like IPs and User Agents or disabling logging data completely.

It would be great if that was somehow configurable, just some ideas:

- Options to e.g. truncate the IPs or not store the User Agent.
- A filter that let's me manipulate the complete logging data myself, e.g. [here](https://github.com/download-monitor/download-monitor/blob/ea0672270513e2b82addb95f4d5e7c0c8ebfbf78/includes/class-dlm-logging.php#L56-L67)
- Dedicated filters for stuff that makes sense, e.g. [the IP](https://github.com/download-monitor/download-monitor/blob/ea0672270513e2b82addb95f4d5e7c0c8ebfbf78/includes/class-dlm-utils.php#L11)

But I am not sure what side-effects that might have, like with the unique IP logging feature. Looking forward to your thoughts.

**Comment by barrykooij** [comment]
Logging will be re-done for a big chunk in 4.0. Will look into this for 4.0

**Comment by barrykooij** [comment]
This will be possible in `4.0` with the `dlm_log_item` filter.

https://github.com/download-monitor/download-monitor/blob/4.0/src/DownloadHandler.php#L358
