### ISSUE TITLE
Download logs not updated

### ISSUE THREAD

**Issue by dinakaranAppViewX** [download-monitor/download-monitor#411]
Hi,

I am using download monitor for more than 3 months, I found this issue yesterday. The things is if user logged in and download any file the log was not created. I have unchecked Count unique IPs only in logging. But still log is not updated.

**Comment by barrykooij** [comment]
I suspect that there is a plugin or theme conflict on your website. Could you please try if the error still occurs with only this plugin activated with a default WordPress theme (e.g. twentyfifteen). I understand this can be a bit of a hassle but it's the only way we can be sure it's a bug in this plugin.

**Comment by barrykooij** [comment]
No reply for months, closing.
