### ISSUE TITLE
A bug on the list of all downloads

### ISSUE THREAD

**Issue by i22lomoa** [download-monitor/download-monitor#412]
It is not displayed, the featured, only for members or redirect downloads.
![image](https://user-images.githubusercontent.com/7048620/28305867-a1f442bc-6b9d-11e7-8952-0416f253fedf.png)

**Comment by barrykooij** [comment]
Just tested this and can't reprocude this locally. I suspect that there is a plugin or theme conflict on your website. Could you please try if the error still occurs with only this plugin activated with a default WordPress theme (e.g. twentyfifteen). I understand this can be a bit of a hassle but it's the only way we can be sure it's a bug in this plugin.

![image](https://user-images.githubusercontent.com/2846594/28966261-7e53adfe-7915-11e7-9762-e848c324eda7.png)
