### ISSUE TITLE
Divi visual editor conflict

### ISSUE THREAD

**Issue by barrykooij** [download-monitor/download-monitor#415]
The Divi visual editor fails to load with Download Monitor active.

**Comment by baguapalm** [comment]
Looking forward to have the fix!

**Comment by barrykooij** [comment]
I was able to replicate this in version 3.0.71. The authors of DIVI sent me their latest build (Version: 3.0.78) and the issue appears to be resolved now.

Turned out to be an error on their end after all. Update the DIVI theme and all should be good!

**Comment by uomoragno88** [comment]
In my site the problem persist:

Download Monitor 1.9.8
Divi version 3.0.78

Only disabling Download Monitor the Divi visual editor load  and work fine!

**Comment by baguapalm** [comment]
Same for me!

**Comment by baguapalm** [comment]
http://jmp.sh/dgayz7i

**Comment by barrykooij** [comment]
Are there any JavaScript errors on the page?

**Comment by baguapalm** [comment]
The console shows this: http://jmp.sh/hhnSEKX

**Comment by baguapalm** [comment]
Still no fix? I need this functionnality on my website.

Thanks
