### ISSUE TITLE
get_pages() is ran on every page load in admin

### ISSUE THREAD

**Issue by TeemuSuoranta** [download-monitor/download-monitor#416]
Hi!

I noticed a noticeable speed issue in Download Monitor plugin. On every page load in admin DM setups the settings in /includes/admin/class-dlm-admin.php

Here the plugin will run get_pages() every time which will take some time if you happen to have a site with hundreds of pages. This page info is not needed everywhere.

A few ways to fix this:
- Load get_pages only in the setting view where you need it
- Put pages in transient (you may need to look out for multilingual sites)
- Put the whole settings array in transient (again, you may need to look out for multilingual sites)

If you want help, I can also make this into pull request.

**Comment by TeemuSuoranta** [comment]
Here's the exact line where this happens https://github.com/download-monitor/download-monitor/blob/master/includes/admin/class-dlm-admin.php#L264

**Comment by barrykooij** [comment]
Thanks for reporting this. I'll look into this for the 1.9.8 patch.

**Comment by barrykooij** [comment]
I've introduced a 'lazy select' option for Download Monitor settings. Options of these select elements are only loaded on setting pages, increasing overall plugin performance. Options will be rewritten in upcoming 4.0 release but this will be a good performance boost until then.
