### ISSUE TITLE
OSX recursive download

### ISSUE THREAD

**Issue by danielng01** [download-monitor/download-monitor#418]
When the download is not set to 
Redirect to file

On OSX the download fails and the download counter increments until cancel the download url request

**Comment by barrykooij** [comment]
@hchouhan can you please try to re-produce this issue on OSX?

**Comment by hchouhan** [comment]
@barrykooij Tested on Chrome, Firefox & Safari on Mac OSX and for a download which is not set "Redirect To File" the download works as expected.

@danielng01 Can you please share more steps to reproduce the issue?

**Comment by danielng01** [comment]
@hchouhan I think it was ok when the download was on my server, but I use URL from github, example:
https://github.com/danielng01/Iris-Builds/raw/master/OSX/Iris-0.9.2.6-OSX.zip
as Download file and Redirect to file is unchecked

**Comment by barrykooij** [comment]
@danielng01 thanks for the extra information. If the file is remote, you can indeed only use the "redirect to file" option. So this is expected behavior. We'll look into making this more clear in our documentation.
