### ISSUE TITLE
Fatal error: Class 'GF_Fields' not found class-dlm-gf-gravity-forms-handler.php on line 38

### ISSUE THREAD

**Issue by johncrumpton** [download-monitor/download-monitor#419]
Upgraded to the latest Gravity Forms and received white screen and this error

`Fatal error: Class 'GF_Fields' not found in /home/x/wp-content/plugins/dlm-gravity-forms/classes/class-dlm-gf-gravity-forms-handler.php on line 38`

**Comment by barrykooij** [comment]
Hey @johncrumpton ,

This sounds like an error in one of our extensions. Please contact support via https://www.download-monitor.com/contact/

Kind Regards,

Barry Kooij
