### ISSUE TITLE
PDF Thumbnail Error

### ISSUE THREAD

**Issue by hchouhan** [download-monitor/download-monitor#420]
Errors are logged because WordPress tries to generate thumbnails for PDFs that have been uploaded to Download Monitor. This happens when a user opens the Media Manager on a post and there is a PDF stored in Download Monitor. The thumbnail generation appears to be calling the PDF over the web and hitting the deny from all htaccess file.

https://wordpress.org/support/topic/pdf-thumbnail-error/

**Comment by barrykooij** [comment]
I'll look into if we can ask WP not to generate thumbnails.
