### ISSUE TITLE
Download->exists() does not require status to be published

### ISSUE THREAD

**Issue by barrykooij** [download-monitor/download-monitor#427]
Currently Download's do not need to be published in order to _exist_. This causes trashed downloads also to return `true` on the `exists()` check. This should be changed since a trashed download should no longer _exists_ in the eyes of the system.

**Comment by KZeni** [comment]
I have also come across this issue. It appears downloads that are a draft are also accessible.

As an aside, the use of the rewrite URL for a download as mentioned in https://github.com/download-monitor/download-monitor/pull/410 results in a download URL that *_does_* provide the download according to its published status as you'd expect (drafts, etc. show the 404 page unless logged in.)
