### ISSUE TITLE
Download ID showing in Google Search

### ISSUE THREAD

**Issue by GhKings** [download-monitor/download-monitor#430]
Download links keeping showing in google search even though Googlebot is blacklisted. They are appear as such ../download-id/7232/ even though I changed the endpoint to ../song/0000

**Comment by barrykooij** [comment]
Are you sure this is caused by Download Monitor? Because our default endpoint is `/download/` and not `/download-id/`. Do you have an example page that is listed in google?

**Comment by GhKings** [comment]
Here are screenshots; ![a search on our website with Google search enabled](https://user-images.githubusercontent.com/16061547/32251628-c0ba45ae-be89-11e7-85af-cc4df2d9a391.png)
![direct Google search](https://user-images.githubusercontent.com/16061547/32251648-d742a816-be89-11e7-838a-50018cd1e83c.png)

**Comment by barrykooij** [comment]
What version of Download Monitor are you using?

**Comment by GhKings** [comment]
I'm using the version 1.9.9.

**Comment by barrykooij** [comment]
These look like AMP links. Are you using a SEO or AMP plugin?

**Comment by barrykooij** [comment]
I'm closing this issue due to no response in almost 2 months. Please do let me know if this issue still persists.
