### ISSUE TITLE
Wordpress 4.9.1 and download monitor 1.9.9: 404 problem

### ISSUE THREAD

**Issue by erotavlas85** [download-monitor/download-monitor#452]
Hi,
I'm having a problem with latest version of download monitor and wordpress. I'm using the same configuration and the same version of both plugin and wordpress in other hosting, but without SSL and it works well. Is your plugin compatible with SSL?
At the moment when I click in a URL provided by shortcode in a website with SSL it gives back 404 page not found.
Thank you

**Comment by barrykooij** [comment]
The plugin works with SSL but does store absolute paths. So if you added the downloads prior SSL, you need to update your downloads when moving to SSL. I recommend using a database find & replace plugin / tool for this.

**Comment by erotavlas85** [comment]
Hi,

I installed my wordpress Web site directly into SSL version. So the problem is another one. Moreover, I have another wordpress Web site for which I change from HTTP to HTTPS and it worked without any change in the database. I'm still thinking that there is a compatibility problem between polylang and your plugin.

Thank you for your effort.
