### ISSUE TITLE
php 7.1 compatibility errors

### ISSUE THREAD

**Issue by marties** [download-monitor/download-monitor#454]
hi,
running PHP Compatibility Checker gives me these errors and warnings :
this warning many times: 

`Function name "__download_monitor_install" is discouraged; PHP has reserved all method names with a double underscore prefix for future use`

`FILE: /wp-content/plugins/download-monitor/includes/admin/uaparser/uaparser-test.php
ERROR | Indirect access to variables, properties and methods will be evaluated strictly in left-to-right order since PHP 7.0. Use curly braces to remove ambiguity.`

Hope that helps

**Comment by barrykooij** [comment]
Thanks for letting me know. Patching this in coming update

**Comment by barrykooij** [comment]
This should be fixed in 4.0
