### ISSUE TITLE
Allow Proxy IP Override Not Working

### ISSUE THREAD

**Issue by rizonesoft** [download-monitor/download-monitor#464]
When I enable the 'Allow Proxy IP Override' function, I get the following error:

Notice: Only variables should be passed by reference in /home/wp_e7q445/rizonesoft.com/wp-content/plugins/download-monitor/src/Utils.php on line 11

Warning: Cannot modify header information - headers already sent by (output started at /home/wp_e7q445/rizonesoft.com/wp-content/plugins/download-monitor/src/Utils.php:11) in /home/wp_e7q445/rizonesoft.com/wp-content/plugins/download-monitor/src/CookieManager.php on line 56

Warning: Cannot modify header information - headers already sent by (output started at /home/wp_e7q445/rizonesoft.com/wp-content/plugins/download-monitor/src/Utils.php:11) in /home/wp_e7q445/rizonesoft.com/wp-content/plugins/download-monitor/src/DownloadHandler.php on line 477

**Comment by barrykooij** [comment]
Looks like the `array_shift` is causing this issue in `DLM_Utils::get_visitor_ip()`. This is no longer a problem in modern PHP version but is up until 5.3 (I think). Should fix this for DLM since WP is still 5.2.x compat.

**Comment by barrykooij** [comment]
https://github.com/download-monitor/download-monitor/blob/master/src/Utils.php#L11

**Comment by rizonesoft** [comment]
@barrykooij Thank you for your speedy reply. I temporarely fixed it with the following mod:

`public static function get_visitor_ip() {
		$rizonesoft_fix = explode( ",", $_SERVER['HTTP_X_FORWARDED_FOR'] );
		return sanitize_text_field( ( ( '1' == get_option( 'dlm_allow_x_forwarded_for', 0 ) ) && ! empty( $_SERVER['HTTP_X_FORWARDED_FOR'] ) ) ? trim( array_shift( $rizonesoft_fix ) ) : $_SERVER['REMOTE_ADDR'] );
	}`

**Comment by barrykooij** [comment]
thanks @rizonesoft, I'll work on a patch today for this.
