### ISSUE TITLE
Check if 'dlm_download' posts already exists when showing legacy upgrade message

### ISSUE THREAD

**Issue by barrykooij** [download-monitor/download-monitor#466]
When people have already upgraded from legacy in the past with our (no longer available) legacy upgrader extension, the upgrade notification is still shown. When they run the new build-in upgrader, all legacy downloads will be added *again*.

Check if there are already `dlm_download` posts and if there are, don't show the notification.

**Comment by bwklein** [comment]
Not only that, but if you mistakenly allow the upgrader to run, it will set all your shortcodes in all your site content to [download id=0] which takes a REALLY long time to fix if you didn't backup your database first.

**Comment by barrykooij** [comment]
@bwklein yeah this upgrader was totally not build to be run when the user already upgraded manually. Hopefully everyone made a backup since the tool warns the user to do it like 3 times before it starts.

**Comment by bwklein** [comment]
I know for certain that not everyone did.  I thought that the 'repairs' were updating something in the download manager tables, I didn't realize that it was going to be a rewrite of all shortcodes in all my content.  It took 7 years of using Wordpress to finally get hit with a need to have backed up first on an update.  Lesson learned.

**Comment by barrykooij** [comment]
@bwklein I'm very sorry to hear that. It's not of any help to you but I'm adding more checks to this to prevent users from running the upgrader when they already manually upgraded before. It might be worth contacting your host and see if they have a nightly backup of your database (most hosts do).

**Comment by barrykooij** [comment]
Fixed by 4a7e0ceb5099abad273ac9057aac8f592b59acbc & b260aae34be253eb9c045112d6b06c12d2584cc1
