### ISSUE TITLE
Download link giving error

### ISSUE THREAD

**Issue by nagarajagundappa** [download-monitor/download-monitor#468]
The download short codes and URLs that were working earlier have all started throwing up an error all of a sudden. Following is the screenshot:

![image](https://user-images.githubusercontent.com/35793578/35373747-e1869bfa-01c5-11e8-9d56-4ecea20ec75d.png)

**Comment by barrykooij** [comment]
Hey there,

Looks like the upgrade was unable to ALTER your database table. Please contact your host and check if your WordPress website is allowed to `ALTER` database tables. If not, ask your host to run the following SQL queries on your database:

```
 "ALTER TABLE wp_download_log CHANGE `download_date` `download_date` DATETIME NULL DEFAULT NULL;" 
 "ALTER TABLE wp_download_log ADD `meta_data` LONGTEXT NULL DEFAULT NULL AFTER `download_status_message`;" 
"ALTER TABLE wp_download_log DROP `type`;" 
```

Note that `wp_download_log` is the default name for your table, your host might use a different table prefix (but they should know about this).

Kind Regards,

Barry Kooij
