### ISSUE TITLE
has_ip_downloaded_version column type unknow

### ISSUE THREAD

**Issue by plaurent75** [download-monitor/download-monitor#470]
DLM_Logging->has_ip_downloaded_version

SELECT COUNT(ID) FROM {$wpdb->download_log} WHERE type = 'download'

Type column dos not exist

Also, the comment says : Check if visitor has downloaded version in the past 24 hours
But nothing seems to select date range in this request ?

**Comment by barrykooij** [comment]
Hey,

Did you update all your extension to `4.0` as well? This looks like an old query where the `type` column still existed in the database table.

Kind Regards,

Barry Kooij

**Comment by barrykooij** [comment]
Fixed via https://github.com/download-monitor/download-monitor/issues/476
