### ISSUE TITLE
Downloadable file link is not saved

### ISSUE THREAD

**Issue by enricator** [download-monitor/download-monitor#479]
I am experiencing an annoying issue on a website with WordPress 4.9.3 and Download Monitor 4.0.2
When I try to create a new download (and I tried with any file type and with different sizes) it does create a new download item with the correct title and category, but the downloadable file link is not saved, and a second item with “Download #xxx File Version” is created (always with missing file/version link).
This is a snapshot of what I see:
![image](https://user-images.githubusercontent.com/3007746/35975657-ba6f5566-0cdd-11e8-87d7-e695678d218e.png)

I can see the file in the dlm_uploads folder

I have the same issue if I create a new download and choose an existing file (uploaded with download-monitor in the past months)

I can't seem to add any new downloads :(

**Comment by hchouhan** [comment]
Hello,

Can you please email us at support@download-monitor.com so we can test your settings?

**Comment by barrykooij** [comment]
Hey @enricator ,

I suspect that there is a plugin or theme conflict on your website. Could you please try if the error still occurs with only this plugin activated with a default WordPress theme (e.g. twentyfifteen). I understand this can be a bit of a hassle but it's the only way we can be sure it's a bug in this plugin.

Kind Regards,

Barry Kooij

**Comment by enricator** [comment]
Ok, I'm making a local copy of the website and I will try it.
I will let you know soon.

**Comment by enricator** [comment]
Hi @barrykooij, 

this is a first update of all the tests I took on my local webserver, with WordPress 4.9.4:

- First I tried deactivating all the plugins except Download Monitor 4.0.3 and I was able to add a new download.

- So I reactivated all the plugins and adding new downloads worked as well.

- Then, with all plugins activated, I tried adding a new download without publishing it, saving it as a new draft, and the downlodable files disappeared (see image)
![image](https://user-images.githubusercontent.com/3007746/36160043-83aaabf0-10e0-11e8-854e-327df050dc41.png)
At the same time a new "download #xxx File Version" appeared in the "all the downloads" list
![image](https://user-images.githubusercontent.com/3007746/36160305-1f6226fe-10e1-11e8-8e87-d0e20835a93f.png)
I had the same problem editing an existing (working) download and uploading a new file version

- So I deactivated all of the plugins once again, and selected the twentyfifteen theme: adding a new download worked, editing an existing download worked, but saving a new draft results in no downloadable file and a new download item with a title of "download #xxx file version" (and no file as well) 

- Lastly I tried editing the last draft (the last one I added, with no file), I chose an existing file instead of uploading it (I used one in the dlm_uploads folder), and when I hit "publish" everything worked correctly


Seems to me that the "save as draft" might have an issue 


Tomorrow I will try and reactivate one plugin at a time, repeating all the tests each time, in order to check if the problem is only in the "draft" or "update" mode, and if other plugins interfere

**Comment by enricator** [comment]
I confirm what phreesurf wrote [here on wordpress.org](https://wordpress.org/support/topic/cannot-upload-file-creating-download-xxx-file-version-downloads/#post-9971101):

looks like the [Post Type Switcher](https://wordpress.org/plugins/post-type-switcher/) might conflict with Download Monitor

**Comment by enricator** [comment]
Update: 
Download Monitor works with PostTypeSwitcher deactivated.

There's only one thing left: the "downloadable files/versions" are not shown when the download is saved in draft mode (this happens even if you change the status from published to draft: the files/versions disappear).

![published download](https://user-images.githubusercontent.com/3007746/36193932-12009f40-1168-11e8-89f7-d1ed2a4a0abb.png)
_published download with file version_

![download in draft](https://user-images.githubusercontent.com/3007746/36193996-4a7697c6-1168-11e8-8b66-bf347638e013.png)
_same download in draft or pending mode does not show file version_

Is this an intentional behaviour?

**Comment by barrykooij** [comment]
@enricator Thanks so much for all your effort, this really helps! I think we found 2 issues in 1. The draft / pending review status should display file versions. I created a separate ticket for this: #480

Let's keep this ticket to file versions being detached from downloads, most likely due to a conflict with PostTypeSwitcher

**Comment by barrykooij** [comment]
The conflict with `post-type-switcher` is fixed in their plugin's master branch and will hopefully be released soon.

Reported issue on their repo: https://github.com/JJJ/post-type-switcher/issues/9
