### ISSUE TITLE
Versioning not working in download-version-list.php template

### ISSUE THREAD

**Issue by barrykooij** [download-monitor/download-monitor#489]
https://wordpress.org/support/topic/problem-with-downloading-versions/#post-10044754

**Comment by jamesgol** [comment]
I fixed this in #485

**Comment by barrykooij** [comment]
This is caused by this commit: https://github.com/download-monitor/download-monitor/commit/d46d60ea99cfd28dc6701553ce6dcac9576afeb3#diff-66297343e2dded3ce53e002c5621a2a5

The issue is I removed the `$dlm_download->set_version( $version->id );` and didn't place it back. This is causing the download not the 'know' we want version information in the loop.
