### ISSUE TITLE
Limiting how many downloads show under "Popular Downloads" dashboard widget

### ISSUE THREAD

**Issue by fredbradley** [download-monitor/download-monitor#493]
Hello, 

I'm sure I'm missing the setting somewhere, but I can't for the life of me work out how to limit the list of "Popular Downloads" on the Admin Dashboard Widget. 

At the moment it's showing everything - every download. Can we get it to only show the 5 or 10 most popular?

Is there a filter I can use to overwrite this setting perhaps?

**Comment by barrykooij** [comment]
4.0.7 will already introduce the `dlm_remove_dashboard_popular_downloads` filter to stop the dashboard from loading at all. I didn't know but apparently if you disable the admin widget in WordPress, WordPress still loads it. 

I'll look into the admin dashboard widget some more, it shouldn't display all downloads I think.

**Comment by barrykooij** [comment]
This was indeed a bug, fixed in 4.0.7
