### ISSUE TITLE
Downloads are visible even to users who do not have access to it

### ISSUE THREAD

**Issue by hchouhan** [download-monitor/download-monitor#494]
When downloads are set to hidden for users who do not have access to them, they are still visible. 

Tickets:
- https://secure.helpscout.net/conversation/544447517/6686?folderId=391866

**Comment by barrykooij** [comment]
This is an option added by the AAM extension, not something supported in core. The manipulation of the [downloads] shortcode only works for access set by AAM, not 'members only'.
