### ISSUE TITLE
Custom template deleted after each update!

### ISSUE THREAD

**Issue by serdam55** [download-monitor/download-monitor#499]
I have already reported this bug via email but was not fixed yet, anyway, when I update each new version my custom template will be removed from the template folder

**Comment by barrykooij** [comment]
hey @serdam55 ,

That's because you need to place the custom templates in your theme. You can read more about it here: https://www.download-monitor.com/kb/overriding-content-templates/

Never change the files withint the `/plugins/download-monitor/` folder.

Kind Regards,

Barry Kooij
