### ISSUE TITLE
Bug with WPML in secondary domains

### ISSUE THREAD

**Issue by eduarroyo05** [download-monitor/download-monitor#500]
Hi there. 

I'm using your plugin in a Multilanguage site with WPML, with domains. I'm having an issue when trying to download an archive in secondary domians. Seems that the plugin look for the download in the primary domain, so I get an error and I can't download the archive.

Con you help me? Thanks!

**Comment by barrykooij** [comment]
This sounds like an issue with WPML. Please contact their support or consider switching to a multilingual solution that uses a different approach.
