### ISSUE TITLE
Error 404 on all downloads since the last update

### ISSUE THREAD

**Issue by Perlipopette** [download-monitor/download-monitor#509]
Hi there,

Well, the issue's in the title. We got an error 404 on all uploads even the new ones, since the last update. 

Could you please help ?

Thanks, have a nice & bright day !
Marina

**Comment by barrykooij** [comment]
Hey Marina,

I'm sorry to hear that! Could you try re-saving the permalinks? You can do so by going to WordPress default settings > permalinks and click the 'Save changes' button. This usually resolves the issue. 

Kind Regards,

Barry Kooij

**Comment by Perlipopette** [comment]
Yey ! Thank you Barry :o) I love the moments when something that seemed so complicated becomes soooo simple :o)
