### ISSUE TITLE
Since last update new downloads produce a 404 error

### ISSUE THREAD

**Issue by rickyelqasem** [download-monitor/download-monitor#515]
I can see the file is being uploaded to the new dlm_upload folder but I cannot access the link and throws a 404 error. Obviously a permissions thing but I cannot find it as the permissions look the same as the old folders. 

http://blog.cloudnativeplanet.com/wp-content/uploads/dlm_uploads/2018/06/AstrApp.zip

**Comment by Alekuoshu** [comment]
I have the same problem, somebody helpme?

**Comment by rickyelqasem** [comment]
Support helped me out and it was because there is "index.php" in your permalinks in side wordpress settings.

**Comment by Alekuoshu** [comment]
Sorry, I dont understand yet, can you explain me better?

**Comment by rickyelqasem** [comment]
WPadmin > Settings > Permakinks > do you have a custom permalink with index.php in the url? if so change it to something else. I changed it to "date and name"

**Comment by Alekuoshu** [comment]
Oh, I see, but these its no was solution for me, only I changed the Download Endpoint value on endpoint tab from settings to default value like "download" and that is it. Thank you for comment

**Comment by barrykooij** [comment]
Thanks for helping each other out! I'm closing this now as GitHub is only for bugs and this was resolved via support. For further questions, please got to https://wordpress.org/plugins/download-monitor/
