### ISSUE TITLE
Latest version URL is private but need to export it

### ISSUE THREAD

**Issue by yakuter** [download-monitor/download-monitor#532]
Thanks for this great plugin. I have an issue about retrieving the latest version URL. 

I am using this code to get the $url of the latest version of a product.

```
$versions = download_monitor()->service( 'version_repository' )->retrieve(array('post_parent' => $posts[0]->ID),1);

$DownloadUrl    = $versions[0]->url;
```

However the $version and $url variable is private in your version.php file. So I need to change and make it public to make my code work.

I know this is a wrong solution. Can you tell me what is the best way to do it? Is there anything native whic I am missing?

**Comment by barrykooij** [comment]
hey @yakuter ,

The version repository returns an array of DLM_Download_Version objects, which has the following method:

```get_url()```

So you can do:

```
$DownloadUrl    = $versions[0]->get_url();
```

But if you want the current download url, you can also fetch the download with the download repository (https://www.download-monitor.com/kb/download-repository-retrieve/) and use the ```get_the_download_link()``` method on that DLM_Download object.

Kind Regards,

Barry Kooij

**Comment by yakuter** [comment]
Thanks for your answer, I missed get_url() method. However the object (version variable in version.php) itself is private. So I still can't get the version url. As you guess the error is:

Fatal error: Uncaught Error: Cannot access private property DLM_Download_Version::$version...

**Comment by barrykooij** [comment]
Same story for all variables. Use `get_version()` instead of directly trying to access the property. See full source for all methods: https://github.com/download-monitor/download-monitor/blob/master/src/Version/Version.php

**Comment by yakuter** [comment]
Ohh yes I am really sorry, everything is clear now. I don't know why I didn't figure out that this is a getter setter file. Thanks a lot :)
