### ISSUE TITLE
Question: existing documents

### ISSUE THREAD

**Issue by adrianmoya** [download-monitor/download-monitor#562]
Hi, I have a site with around 100 documents and want to start tracking downloads. Do I have to manually add each document 1 by 1 in the documents tab? or is there a way to tell the plugin to recognize the existing documents?

Thanks,

**Comment by barrykooij** [comment]
You will have to add the files via your WordPress backend. For further supports questions, please use the support forums: https://wordpress.org/support/plugin/download-monitor/

Kind Regards,

Barry Kooij
