### ISSUE TITLE
Download Doesn't Exist

### ISSUE THREAD

**Issue by Budget101** [download-monitor/download-monitor#594]
Wasted hours of time creating new downloads, then went into various posts to add them, only to receive "Download does not Exist, Go to Homepage" errors. On EVERY. SINGLE. ONE of them.

**Comment by barrykooij** [comment]
Hey @Budget101 ,

Please contact us via support@download-monitor.com for support. These issues are intended for confirmed bugs or features we use in our development.

Kind Regards,

Barry Kooij
