### ISSUE TITLE
Updated plug-in not working.

### ISSUE THREAD

**Issue by semide** [download-monitor/download-monitor#597]
We are running a site with DLM and Email Before Download.   We just noticed that although the form works, and the email is sent to Admins, the download link does not work, it leads back to the homepage.  The download link in the DLM admin top right is listed as http://stoneacreaffinity.com/http://stoneacreaffinity.com/download//stoneacre2-0-ebook/, which is obviously wrong, but the file link in the downloads section is correct.  When we use the DLM shortcode, it presents the wrong link.  

We are running latest WP 4.9.1
PHP 5.6.4
DLM 4.4.2
Email Before Download 5.1.9 - although I doubt that is the issue, disabling it or using the DLM shortcode has the same effect.

I tried adding a new version, but the issue persists.

If you have any guidance, I would be appreciative.

**Comment by barrykooij** [comment]
Hey @semide ,

Please contact us via support@download-monitor.com for support. These issues are intended for confirmed bugs or features we use in our development.

Kind Regards,

Barry Kooij
