### ISSUE TITLE
Saving a GB block without selecting a download causing a null error

### ISSUE THREAD

**Issue by barrykooij** [download-monitor/download-monitor#601]

**Comment by hchouhan** [comment]
Send Updates to:
- https://wordpress.org/support/topic/gutenberg-fatal-error-if-block-is-left-empty

**Comment by hchouhan** [comment]
https://secure.helpscout.net/conversation/1407863289/13068/

**Comment by bozzmedia** [comment]
Noting this remains an issue on latest version of production.

More info: 
https://wordpress.org/support/topic/fatal-error-content-download-title-php12/#post-14891592

Full stack trace:
#0 /home/redacted/public_html/wp-content/plugins/download-monitor/src/TemplateHandler.php(90): include()
#1 /home/redacted/public_html/wp-content/plugins/download-monitor/src/Gutenberg.php(111): DLM_Template_Handler->get_template_part('content-downloa...', 'title', '', Array)
#2 /home/redacted/public_html/wp-includes/class-wp-block.php(221): DLM_Gutenberg->render_download_button(Array, '', Object(WP_Block))
#3 /home/redacted/public_html/wp-includes/class-wp-block.php(211): WP_Block->render()
#4 /home/redacted/public_html/wp-includes/class-wp-block.php(211): WP_Block->render()
#5 /home/redacted/public_html/wp-includes/class-wp-block.php(211): WP_Block->render()
#6 /home/redacted/public_html/wp-includes/class-wp-block.php(211): WP_Block->render()
#7 /home/redacted/public_html/wp-includes/blocks.php(868): WP_Block-
