### ISSUE TITLE
Github Security Alerts

### ISSUE THREAD

**Issue by fredbradley** [download-monitor/download-monitor#614]
Github is trying to tell me that your package-lock.json has a bunch of vulnerabilities. 

Will these ever get fixed? 

![image](https://user-images.githubusercontent.com/1639226/70625125-ad91e000-1c19-11ea-9c73-1796daaa797a.png)

**Comment by barrykooij** [comment]
I should look into this. It's low prio because at this point these are not included in the build to users but is simply a dev thing.

**Comment by fredbradley** [comment]
![image](https://user-images.githubusercontent.com/1639226/75040862-5d55ba80-54b3-11ea-95ae-28f5183da36e.png)

Just a nudge, is the response the same?

**Comment by barrykooij** [comment]
Yeah these are development packages, none of these are shipped to clients. You only have these packages installed if you run `npm install`
