### ISSUE TITLE
Notice php 7.4

### ISSUE THREAD

**Issue by barrykooij** [download-monitor/download-monitor#620]
[error] 2148#2148: *285 FastCGI sent in stderr: "PHP message: PHP Notice: Trying to access array offset on value of type bool in /www/xxxxxx/public/wp-content/plugins/download-monitor/src/DLM.php on line 236" while reading response header from upstream, client: xxxxxx, server: xxxxxx,, request: "GET /en/ HTTP/1.0", upstream: "fastcgi://unix:/var/run/php7.4-fpm-xxxxxx.sock:", host: "xxxxxx", referrer: "xxxxxx"

**Comment by hchouhan** [comment]
- https://wordpress.org/support/topic/php-7-4-error-notice/

**Comment by hchouhan** [comment]
https://secure.helpscout.net/conversation/1158493268/11919/

**Comment by hchouhan** [comment]
https://wordpress.org/support/topic/php-error-400/

**Comment by deltafactory** [comment]
Let me propose my post from the forum as a possible solution: https://wordpress.org/support/topic/php-error-400/#post-13100612

> 
> Not knowing all of the possible values from `get_theme_support()` line 236 may be incorrect:
> 
> `if ( is_array( $current_support[0] ) ) {`
> 
> might need to become:
> 
> `if ( is_array( $current_support ) ) {`
>

**Comment by hchouhan** [comment]
Another error:

`PHP Deprecated: Function get_magic_quotes_runtime() is deprecated in .../wp-content/plugins/download-monitor/src/DownloadHandler.php on line 612`

**Comment by hchouhan** [comment]
https://wordpress.org/support/topic/php-deprecated-function-get_magic_quotes_runtime-is-deprecated/

**Comment by hchouhan** [comment]
https://wordpress.org/support/topic/php-deprecated-warnings/

**Comment by hchouhan** [comment]
https://wordpress.org/support/topic/php-errors-in-ajax-response-bug/

**Comment by jkroepke** [comment]
Any plan for php 7.4? Ubuntu default PHP version is 7.4.

**Comment by hchouhan** [comment]
https://secure.helpscout.net/conversation/1296113442/12607?folderId=919809
