### ISSUE TITLE
Pass variables to dlm_downloadable_file_version_table_start and dlm_downloadable_file_version_table_end actions

### ISSUE THREAD

**Issue by davidsherlock** [download-monitor/download-monitor#625]
Two actions are available in the versions.php metabox file:

`dlm_downloadable_file_version_table_start`
`dlm_downloadable_file_version_table_end`

Neither of these pass in any variables such as the version or file ID so I can't add a new field and populate it properly without a lot of messing around. If these 3 variables were passed to the actions it would make life a lot easier for my project:

`$file_version`, `$version_increment`, `$file_id`

I can submit a pull request for this.

**Comment by davidsherlock** [comment]
Only these two are required:

`$file_id`, `$version_increment`

**Comment by davidsherlock** [comment]
#626 pull request submitted.

**Comment by barrykooij** [comment]
merged, will be included in 4.4.4
