### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by pretfred** [download-monitor/download-monitor#640]
I get this error. Tried to delete download monitor en reinstall, but that didn't work. 
I've got the latest version of WordPress and everything else is up to date.

Notice: Trying to access array offset on value of type bool in /home/website/domains/domain/public_html/webshop/wp-content/plugins/download-monitor/src/DLM.php on line 236
Thank you

**Comment by barrykooij** [comment]
Will be fixed in 4.4.4
