### ISSUE TITLE
Unable to lock file with ninja form

### ISSUE THREAD

**Issue by annawill** [download-monitor/download-monitor#641]
We want to use Download Monitor - Ninja Forms Extension to protect our downloads. Website visitors should be able to access the selected download by filling out a Ninja Form. 

I used the shortcode [dlm_nf_form download_id=xx] of the download to integrate it into my site. When I try to download this file, I get this error message: "You do not have permission to access this download. Go to homepage".

Download Monitor works when the extension "Download Monitor - Ninja Forms Extension" is disabled.

**We use:**
Download Monitor: 4.4.3
Download Monitor - Ninja Forms Extension: 4.0.0
WordPress: 5.5.1 
Ninja Forms: 3.4.30

Could you please help me in this? Thank you!

**Comment by barrykooij** [comment]
Hey @annawill ,

Sorry for the late reply, we use this issue tracker for issues with our core plugin. For help with our extensions, please send us a message at support@download-monitor.com

Cheers,

Barry
