### ISSUE TITLE
using this plugin in my project

### ISSUE THREAD

**Issue by shahreahang** [download-monitor/download-monitor#655]
Hello,
one of my customers use this plugin to create a shortcut (link) to another website for download, my question is how can i use this plugin to create links and forward them to original link from my plugin ? Is there any function for this ?

**Comment by barrykooij** [comment]
Sorry but this is not the place for questions or support. Github is used only to report bugs, please go to our plugin forum for support: https://wordpress.org/support/plugin/download-monitor/
